/**
 * Comprehensive DSA Interview Problem Database (~100 canonical interview problems)
 * Structured for visual algorithm learning, optimization coaching, pattern recognition, and interview prep.
 */

export const dsaCategories = [
  { id: 'arrays', label: 'Arrays', icon: '📦', description: 'Indexed collections, prefix manipulations, and array scanning.' },
  { id: 'strings', label: 'Strings', icon: '📝', description: 'Character sequence processing, palindromes, and parsing.' },
  { id: 'sliding-window', label: 'Sliding Window', icon: '🪟', description: 'Dynamic subsegments for contiguous arrays and strings.' },
  { id: 'two-pointers', label: 'Two Pointers', icon: '👉', description: 'Inward, outward, or parallel pointer convergence.' },
  { id: 'binary-search', label: 'Binary Search', icon: '🔍', description: 'Logarithmic search over sorted or monotonic search spaces.' },
  { id: 'sorting', label: 'Sorting', icon: '🔀', description: 'Comparison sorting, partitioning, and non-comparison algorithms.' },
  { id: 'recursion', label: 'Recursion', icon: '🔄', description: 'Self-referential function decomposition and base-case reasoning.' },
  { id: 'backtracking', label: 'Backtracking', icon: '🌲', description: 'State-space exploration with prune and undo logic.' },
  { id: 'linked-lists', label: 'Linked Lists', icon: '🔗', description: 'Pointer traversal, list reversing, and cycle detection.' },
  { id: 'stacks', label: 'Stacks', icon: '🥞', description: 'LIFO processing, bracket matching, and monotonic stacks.' },
  { id: 'queues', label: 'Queues', icon: '🚶', description: 'FIFO pipelines, BFS frontiers, and sliding window deques.' },
  { id: 'trees', label: 'Trees', icon: '🌳', description: 'Hierarchical node traversal, DFS, BFS, and subtree properties.' },
  { id: 'bst', label: 'BST', icon: '🌿', description: 'Binary Search Tree invariants and logarithmic lookups.' },
  { id: 'heaps', label: 'Heaps', icon: '⛰️', description: 'Priority queues, top-K selection, and streaming medians.' },
  { id: 'graphs', label: 'Graphs', icon: '🌐', description: 'Adjacency structures, BFS/DFS traversal, and shortest paths.' },
  { id: 'greedy', label: 'Greedy', icon: '⚡', description: 'Locally optimal choices leading to global optimization.' },
  { id: 'dp', label: 'Dynamic Programming', icon: '🧩', description: 'Overlapping subproblems and optimal substructure tabulation.' },
  { id: 'bit-manipulation', label: 'Bit Manipulation', icon: '01', description: 'Bitwise XOR, masking, and binary representation tricks.' },
  { id: 'prefix-sum', label: 'Prefix Sum', icon: '➕', description: 'Cumulative range queries and subarray arithmetic.' },
  { id: 'intervals', label: 'Intervals', icon: '↔️', description: 'Time ranges, interval merging, and scheduling overlaps.' },
  { id: 'matrix', label: 'Matrix', icon: '▦', description: '2D grid coordinates, transformations, and spiral traversals.' },
  { id: 'trie', label: 'Trie', icon: '🔤', description: 'Prefix trees for auto-completion and word dictionary search.' },
  { id: 'union-find', label: 'Union Find', icon: '🔗', description: 'Disjoint set union for connected components and cycles.' },
  { id: 'math', label: 'Math', icon: '📐', description: 'Number theory, modular arithmetic, and geometric reasoning.' },
]

export const dsaProblems = [
  // 1. ARRAYS
  {
    id: 'two-sum',
    title: 'Two Sum',
    category: 'arrays',
    difficulty: 'Easy',
    tags: ['Array', 'Hash Table'],
    problemStatement: {
      description: 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target. You may assume that each input would have exactly one solution, and you may not use the same element twice.',
      exampleInput: 'nums = [2, 7, 11, 15], target = 9',
      exampleOutput: '[0, 1]',
      constraints: '2 <= nums.length <= 10^4\n-10^9 <= nums[i] <= 10^9\nOnly one valid answer exists.',
    },
    bruteForce: {
      explanation: 'Check every possible pair (i, j) in the array using nested loops to see if nums[i] + nums[j] equals target.',
      code: `function twoSumBrute(nums, target) {\n  for (let i = 0; i < nums.length; i++) {\n    for (let j = i + 1; j < nums.length; j++) {\n      if (nums[i] + nums[j] === target) {\n        return [i, j];\n      }\n    }\n  }\n  return [];\n}`,
      timeComplexity: 'O(N²)',
      spaceComplexity: 'O(1)',
      pros: 'Simple to understand and implement without extra memory.',
      cons: 'Slow quadratic time due to repeated inner scanning.',
    },
    betterSolution: {
      explanation: 'Sort the array together with original indices, then use left and right pointers to converge towards the target sum.',
      code: `function twoSumBetter(nums, target) {\n  const indexed = nums.map((v, i) => ({ v, i })).sort((a, b) => a.v - b.v);\n  let l = 0, r = indexed.length - 1;\n  while (l < r) {\n    const sum = indexed[l].v + indexed[r].v;\n    if (sum === target) return [indexed[l].i, indexed[r].i];\n    else if (sum < target) l++;\n    else r--;\n  }\n  return [];\n}`,
      timeComplexity: 'O(N log N)',
      spaceComplexity: 'O(N)',
      pros: 'Avoids nested loops and introduces two-pointer reasoning.',
      cons: 'Requires sorting which takes O(N log N) time and O(N) index bookkeeping.',
    },
    optimalSolution: {
      explanation: 'Use a HashMap to store visited numbers and their indices. For each number, check if target - num already exists in the map in O(1) time.',
      code: `function twoSumOptimal(nums, target) {\n  const map = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    const complement = target - nums[i];\n    if (map.has(complement)) {\n      return [map.get(complement), i];\n    }\n    map.set(nums[i], i);\n  }\n  return [];\n}`,
      timeComplexity: 'O(N)',
      spaceComplexity: 'O(N)',
      pros: 'Single-pass linear time with instant hash lookups.',
      cons: 'Uses O(N) auxiliary space for the hash table.',
    },
    interviewTips: {
      whenToThink: 'Whenever you need to find complementary pairs or look up a matching value in constant time.',
      commonMistakes: 'Using the same element twice (e.g. checking map before checking if index !== current index in a two-pass approach).',
    },
    patternRecognition: {
      patternName: 'Hashing & Complement Lookup',
      whyThisPattern: 'Searching for an item in an unsorted array takes O(N) time. By trading O(N) space for a hash table, lookups drop to O(1).',
    },
    optimizationCoach: {
      bottleneck: 'In Brute Force, for each number we scan the remaining array linearly, wasting time looking for target - num.',
      optimizationIdea: 'Store numbers as we visit them in a HashMap so checking for the complement is instantaneous.',
      visualTransition: 'O(N²) Nested Loops ➔ O(1) HashMap Complement Lookup ➔ O(N) Total Time',
    },
    visualComplexity: {
      type: 'quadratic-to-linear',
      stepsExplanation: 'Brute force checks N*(N-1)/2 pairs. The HashMap approach checks N elements exactly once.',
    },
    learningSteps: [
      { step: 1, text: 'We start at index 0 with nums[0] = 2. Complement needed: 9 - 2 = 7.' },
      { step: 2, text: 'HashMap is empty. We store key 2 -> index 0 in the map.' },
      { step: 3, text: 'Move to index 1 with nums[1] = 7. Complement needed: 9 - 7 = 2.' },
      { step: 4, text: 'HashMap contains key 2 at index 0! Match found immediately.' },
      { step: 5, text: 'Return pair indices [0, 1]. Total iterations: 2.' },
    ],
  },
  {
    id: 'best-time-to-buy-stock',
    title: 'Best Time to Buy and Sell Stock',
    category: 'arrays',
    difficulty: 'Easy',
    tags: ['Array', 'Dynamic Programming'],
    problemStatement: {
      description: 'You are given an array prices where prices[i] is the price of a given stock on the i-th day. You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.',
      exampleInput: 'prices = [7, 1, 5, 3, 6, 4]',
      exampleOutput: '5',
      constraints: '1 <= prices.length <= 10^5\n0 <= prices[i] <= 10^4',
    },
    bruteForce: {
      explanation: 'Try every pair of buy day i and sell day j (where j > i) and record the maximum profit.',
      code: `function maxProfitBrute(prices) {\n  let maxP = 0;\n  for (let i = 0; i < prices.length; i++) {\n    for (let j = i + 1; j < prices.length; j++) {\n      maxP = Math.max(maxP, prices[j] - prices[i]);\n    }\n  }\n  return maxP;\n}`,
      timeComplexity: 'O(N²)',
      spaceComplexity: 'O(1)',
      pros: 'Straightforward exhaustive search.',
      cons: 'Time Limit Exceeded on large stock price histories.',
    },
    optimalSolution: {
      explanation: 'Maintain the minimum buying price seen so far and calculate the potential profit on the current day in a single pass.',
      code: `function maxProfitOptimal(prices) {\n  let minPrice = Infinity;\n  let maxProfit = 0;\n  for (let i = 0; i < prices.length; i++) {\n    if (prices[i] < minPrice) {\n      minPrice = prices[i];\n    } else {\n      maxProfit = Math.max(maxProfit, prices[i] - minPrice);\n    }\n  }\n  return maxProfit;\n}`,
      timeComplexity: 'O(N)',
      spaceComplexity: 'O(1)',
      pros: 'Single linear scan with zero extra space.',
      cons: 'Requires understanding running minimum state.',
    },
    interviewTips: {
      whenToThink: 'When you need to find the maximum difference between two elements ordered in time.',
      commonMistakes: 'Selling before buying or resetting minPrice incorrectly.',
    },
    patternRecognition: {
      patternName: 'Running Minimum / Greedy Single-Pass',
      whyThisPattern: 'The optimal buy day for any sell day is always the minimum price seen prior to that sell day.',
    },
    optimizationCoach: {
      bottleneck: 'Brute force checks every sell day for every buy day repeatedly.',
      optimizationIdea: 'Track the running minimum price seen so far. At each day, profit is currentPrice - minPrice.',
      visualTransition: 'O(N²) All Pairs ➔ Track Running Min ➔ O(N) Single Pass',
    },
    visualComplexity: {
      type: 'linear-scan',
      stepsExplanation: 'We inspect each stock price exactly once while updating two scalar variables.',
    },
    learningSteps: [
      { step: 1, text: 'Day 0: price = 7. minPrice becomes 7, profit = 0.' },
      { step: 2, text: 'Day 1: price = 1. New minPrice found (1 < 7). minPrice = 1.' },
      { step: 3, text: 'Day 2: price = 5. Potential profit: 5 - 1 = 4. maxProfit = 4.' },
      { step: 4, text: 'Day 4: price = 6. Potential profit: 6 - 1 = 5. maxProfit = 5.' },
      { step: 5, text: 'Final maxProfit = 5 (buy at 1, sell at 6).' },
    ],
  },
  {
    id: 'maximum-subarray',
    title: 'Maximum Subarray (Kadane’s Algorithm)',
    category: 'arrays',
    difficulty: 'Medium',
    tags: ['Array', 'Dynamic Programming', 'Divide and Conquer'],
    problemStatement: {
      description: 'Given an integer array nums, find the contiguous subarray (containing at least one number) which has the largest sum and return its sum.',
      exampleInput: 'nums = [-2, 1, -3, 4, -1, 2, 1, -5, 4]',
      exampleOutput: '6 (subarray [4, -1, 2, 1])',
      constraints: '1 <= nums.length <= 10^5\n-10^4 <= nums[i] <= 10^4',
    },
    bruteForce: {
      explanation: 'Compute the sum of all possible subarrays by choosing all start and end indices.',
      code: `function maxSubArrayBrute(nums) {\n  let maxS = -Infinity;\n  for (let i = 0; i < nums.length; i++) {\n    let curr = 0;\n    for (let j = i; j < nums.length; j++) {\n      curr += nums[j];\n      maxS = Math.max(maxS, curr);\n    }\n  }\n  return maxS;\n}`,
      timeComplexity: 'O(N²)',
      spaceComplexity: 'O(1)',
      pros: 'Simple to verify.',
      cons: 'Quadratic time scaling.',
    },
    optimalSolution: {
      explanation: 'Kadane’s Algorithm: At each index, decide whether to add the current element to the existing running sum or start a fresh subarray from the current element.',
      code: `function maxSubArrayOptimal(nums) {\n  let currSum = nums[0];\n  let maxSum = nums[0];\n  for (let i = 1; i < nums.length; i++) {\n    currSum = Math.max(nums[i], currSum + nums[i]);\n    maxSum = Math.max(maxSum, currSum);\n  }\n  return maxSum;\n}`,
      timeComplexity: 'O(N)',
      spaceComplexity: 'O(1)',
      pros: 'Optimal linear time and constant auxiliary memory.',
      cons: 'Requires grasping local vs global maximum invariants.',
    },
    interviewTips: {
      whenToThink: 'When searching for an optimal contiguous subarray or sequence sum.',
      commonMistakes: 'Initializing maxSum to 0 instead of nums[0] when all elements can be negative.',
    },
    patternRecognition: {
      patternName: 'Kadane’s Algorithm / DP on Subarrays',
      whyThisPattern: 'A negative prefix sum will only reduce the sum of any future subarray. Discard negative prefixes immediately.',
    },
    optimizationCoach: {
      bottleneck: 'Brute force re-adds elements across overlapping subarray ranges.',
      optimizationIdea: 'If the running prefix sum drops below the current element itself, reset the subarray start.',
      visualTransition: 'O(N²) Subarray Enumeration ➔ Discard Negative Prefixes ➔ O(N) Kadane Scan',
    },
    visualComplexity: {
      type: 'linear-scan',
      stepsExplanation: 'Single loop over N elements. Each element makes an O(1) comparison.',
    },
    learningSteps: [
      { step: 1, text: 'Start with nums[0] = -2. currSum = -2, maxSum = -2.' },
      { step: 2, text: 'Index 1: nums[1] = 1. Math.max(1, -2 + 1) -> start new subarray at 1.' },
      { step: 3, text: 'Index 3: nums[3] = 4. Discard previous negative sum -2, start fresh at 4.' },
      { step: 4, text: 'Indices 4..6: add -1, 2, 1 -> currSum reaches 6!' },
      { step: 5, text: 'Return maxSum = 6 corresponding to [4, -1, 2, 1].' },
    ],
  },
  // 2. STRINGS
  {
    id: 'valid-anagram',
    title: 'Valid Anagram',
    category: 'strings',
    difficulty: 'Easy',
    tags: ['String', 'Hash Table', 'Sorting'],
    problemStatement: {
      description: 'Given two strings s and t, return true if t is an anagram of s, and false otherwise. An Anagram is a word or phrase formed by rearranging the letters of a different word or phrase.',
      exampleInput: 's = "anagram", t = "nagaram"',
      exampleOutput: 'true',
      constraints: '1 <= s.length, t.length <= 5 * 10^4\ns and t consist of lowercase English letters.',
    },
    bruteForce: {
      explanation: 'Sort both strings alphabetically and compare if they are identical.',
      code: `function isAnagramBrute(s, t) {\n  if (s.length !== t.length) return false;\n  return s.split('').sort().join('') === t.split('').sort().join('');\n}`,
      timeComplexity: 'O(N log N)',
      spaceComplexity: 'O(N)',
      pros: 'One-line solution.',
      cons: 'Sorting dominates time complexity.',
    },
    optimalSolution: {
      explanation: 'Use a fixed-size frequency array of 26 English letters. Increment counts for string s and decrement for string t. Check if all counts remain 0.',
      code: `function isAnagramOptimal(s, t) {\n  if (s.length !== t.length) return false;\n  const count = new Array(26).fill(0);\n  for (let i = 0; i < s.length; i++) {\n    count[s.charCodeAt(i) - 97]++;\n    count[t.charCodeAt(i) - 97]--;\n  }\n  return count.every(c => c === 0);\n}`,
      timeComplexity: 'O(N)',
      spaceComplexity: 'O(1)',
      pros: 'Linear time and O(1) space (since alphabet size is bounded by 26).',
      cons: 'Needs character code math.',
    },
    interviewTips: {
      whenToThink: 'When comparing character frequencies or permutations.',
      commonMistakes: 'Forgetting to check if s.length !== t.length before counting.',
    },
    patternRecognition: {
      patternName: 'Frequency Table / Alphabet Counting',
      whyThisPattern: 'Fixed alphabet sizes allow O(1) space frequency histograms.',
    },
    optimizationCoach: {
      bottleneck: 'Sorting characters takes O(N log N) time.',
      optimizationIdea: 'Count character occurrences directly in a 26-slot array.',
      visualTransition: 'O(N log N) Sort ➔ 26-Slot Frequency Map ➔ O(N) Linear Time',
    },
    visualComplexity: {
      type: 'linear-scan',
      stepsExplanation: 'Two characters inspected per index i. Array size 26 is constant.',
    },
    learningSteps: [
      { step: 1, text: 'Check lengths: s.length === 7 and t.length === 7. Proceed.' },
      { step: 2, text: 'Index 0: s[0]="a" (+1 for a), t[0]="n" (-1 for n).' },
      { step: 3, text: 'Continue scanning all 7 characters.' },
      { step: 4, text: 'All increments and decrements cancel out to 0 across all 26 letters.' },
      { step: 5, text: 'Return true.' },
    ],
  },
  // 3. SLIDING WINDOW
  {
    id: 'longest-substring-without-repeating-characters',
    title: 'Longest Substring Without Repeating Characters',
    category: 'sliding-window',
    difficulty: 'Medium',
    tags: ['Hash Table', 'String', 'Sliding Window'],
    problemStatement: {
      description: 'Given a string s, find the length of the longest substring without repeating characters.',
      exampleInput: 's = "abcabcbb"',
      exampleOutput: '3 (substring "abc")',
      constraints: '0 <= s.length <= 5 * 10^4\ns consists of English letters, digits, symbols and spaces.',
    },
    bruteForce: {
      explanation: 'Generate all possible substrings and check if each substring has unique characters.',
      code: `function lengthOfLongestSubstringBrute(s) {\n  let maxLen = 0;\n  for (let i = 0; i < s.length; i++) {\n    const seen = new Set();\n    for (let j = i; j < s.length; j++) {\n      if (seen.has(s[j])) break;\n      seen.add(s[j]);\n      maxLen = Math.max(maxLen, j - i + 1);\n    }\n  }\n  return maxLen;\n}`,
      timeComplexity: 'O(N²)',
      spaceComplexity: 'O(min(N, A))',
      pros: 'Simple double loop.',
      cons: 'Rechecks prefixes repeatedly.',
    },
    optimalSolution: {
      explanation: 'Use a Sliding Window with left and right pointers and a character index map. When a duplicate character is found, jump the left pointer after the last occurrence.',
      code: `function lengthOfLongestSubstringOptimal(s) {\n  const map = new Map();\n  let left = 0, maxLen = 0;\n  for (let right = 0; right < s.length; right++) {\n    if (map.has(s[right])) {\n      left = Math.max(left, map.get(s[right]) + 1);\n    }\n    map.set(s[right], right);\n    maxLen = Math.max(maxLen, right - left + 1);\n  }\n  return maxLen;\n}`,
      timeComplexity: 'O(N)',
      spaceComplexity: 'O(min(N, A))',
      pros: 'Each character is visited at most twice (or once with index jumping).',
      cons: 'Must use Math.max for left pointer to avoid moving left backwards.',
    },
    interviewTips: {
      whenToThink: 'Whenever asked for longest/shortest contiguous substring or subarray with constraints.',
      commonMistakes: 'Not wrapping left in Math.max(left, map.get(char) + 1), which can move left backward.',
    },
    patternRecognition: {
      patternName: 'Dynamic Sliding Window',
      whyThisPattern: 'Instead of starting over when a constraint breaks, shrink/slide the left window border just enough to restore validity.',
    },
    optimizationCoach: {
      bottleneck: 'Brute force restarts the window from i+1 from scratch whenever a duplicate is found.',
      optimizationIdea: 'Keep right pointer moving forward and slide left pointer past the duplicate character.',
      visualTransition: 'O(N²) Substring Generation ➔ Expand Right & Slide Left ➔ O(N) Sliding Window',
    },
    visualComplexity: {
      type: 'window-slide',
      stepsExplanation: 'Right pointer moves N steps. Left pointer only moves forward. Total operations <= 2N.',
    },
    learningSteps: [
      { step: 1, text: 'Window [0..2]: "abc". All characters unique. maxLen = 3.' },
      { step: 2, text: 'Right reaches index 3 ("a"). Duplicate "a" seen at index 0!' },
      { step: 3, text: 'Jump left pointer to index 0 + 1 = 1. Window becomes "bca" (len 3).' },
      { step: 4, text: 'Right reaches index 4 ("b"). Duplicate "b" seen at index 1 -> left becomes 2.' },
      { step: 5, text: 'Scan completes. Maximum valid window length recorded is 3.' },
    ],
  },
  // 4. TWO POINTERS
  {
    id: 'container-with-most-water',
    title: 'Container With Most Water',
    category: 'two-pointers',
    difficulty: 'Medium',
    tags: ['Array', 'Two Pointers', 'Greedy'],
    problemStatement: {
      description: 'You are given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the i-th line are (i, 0) and (i, height[i]). Find two lines that together with the x-axis form a container, such that the container contains the most water.',
      exampleInput: 'height = [1, 8, 6, 2, 5, 4, 8, 3, 7]',
      exampleOutput: '49 (between index 1 and index 8: Math.min(8, 7) * (8 - 1))',
      constraints: 'n == height.length\n2 <= n <= 10^5\n0 <= height[i] <= 10^4',
    },
    bruteForce: {
      explanation: 'Calculate the water area for every possible pair of lines and keep the maximum.',
      code: `function maxAreaBrute(height) {\n  let maxA = 0;\n  for (let i = 0; i < height.length; i++) {\n    for (let j = i + 1; j < height.length; j++) {\n      const area = Math.min(height[i], height[j]) * (j - i);\n      maxA = Math.max(maxA, area);\n    }\n  }\n  return maxA;\n}`,
      timeComplexity: 'O(N²)',
      spaceComplexity: 'O(1)',
      pros: 'Simple exhaustive search.',
      cons: 'Slow O(N²) time on large inputs.',
    },
    optimalSolution: {
      explanation: 'Place two pointers at the leftmost and rightmost ends. The area is limited by the shorter line. Always move the pointer pointing to the shorter line inward to search for a taller boundary.',
      code: `function maxAreaOptimal(height) {\n  let left = 0, right = height.length - 1;\n  let maxA = 0;\n  while (left < right) {\n    const area = Math.min(height[left], height[right]) * (right - left);\n    maxA = Math.max(maxA, area);\n    if (height[left] < height[right]) left++;\n    else right--;\n  }\n  return maxA;\n}`,
      timeComplexity: 'O(N)',
      spaceComplexity: 'O(1)',
      pros: 'Optimal O(N) linear time and O(1) space.',
      cons: 'Requires greedy proof of correctness.',
    },
    interviewTips: {
      whenToThink: 'When optimizing an area or pair metric between two endpoints.',
      commonMistakes: 'Moving the taller line pointer instead of the shorter line pointer.',
    },
    patternRecognition: {
      patternName: 'Two Pointers (Inward Convergence)',
      whyThisPattern: 'Width decreases by 1 on every step. Only increasing the height can overcome a smaller width, so we discard the shorter line.',
    },
    optimizationCoach: {
      bottleneck: 'Brute force checks pairs where both width and height are strictly worse than already seen pairs.',
      optimizationIdea: 'Start at maximum width. Eliminate the shorter wall at each step because no taller partner can ever compensate for the lost width with that short wall.',
      visualTransition: 'O(N²) All Pairs ➔ Move Shorter Pointer Inward ➔ O(N) Linear Scan',
    },
    visualComplexity: {
      type: 'pointer-convergence',
      stepsExplanation: 'Pointers start N-1 units apart and move 1 step inward per iteration until they meet.',
    },
    learningSteps: [
      { step: 1, text: 'Pointers at index 0 (val 1) and index 8 (val 7). Area = min(1, 7) * 8 = 8.' },
      { step: 2, text: 'Left wall (1) is shorter than right wall (7). Move left pointer to index 1 (val 8).' },
      { step: 3, text: 'Now at index 1 (8) and index 8 (7). Area = min(8, 7) * 7 = 49!' },
      { step: 4, text: 'Right wall (7) is shorter. Move right pointer leftward to continue check.' },
      { step: 5, text: 'Maximum area recorded across all convergence steps is 49.' },
    ],
  },
  // 5. BINARY SEARCH
  {
    id: 'binary-search',
    title: 'Binary Search',
    category: 'binary-search',
    difficulty: 'Easy',
    tags: ['Array', 'Binary Search'],
    problemStatement: {
      description: 'Given an array of integers nums which is sorted in ascending order, and an integer target, write a function to search target in nums. If target exists, then return its index. Otherwise, return -1.',
      exampleInput: 'nums = [-1, 0, 3, 5, 9, 12], target = 9',
      exampleOutput: '4',
      constraints: '1 <= nums.length <= 10^4\n-10^4 < nums[i], target < 10^4\nAll integers in nums are unique and sorted.',
    },
    bruteForce: {
      explanation: 'Scan the array from left to right sequentially until target is found.',
      code: `function searchBrute(nums, target) {\n  for (let i = 0; i < nums.length; i++) {\n    if (nums[i] === target) return i;\n  }\n  return -1;\n}`,
      timeComplexity: 'O(N)',
      spaceComplexity: 'O(1)',
      pros: 'Works on unsorted arrays too.',
      cons: 'Does not exploit the sorted order property.',
    },
    optimalSolution: {
      explanation: 'Maintain low and high search bounds. Calculate midpoint mid. If nums[mid] === target, return mid. If less, eliminate left half by setting low = mid + 1; otherwise high = mid - 1.',
      code: `function searchOptimal(nums, target) {\n  let low = 0, high = nums.length - 1;\n  while (low <= high) {\n    const mid = Math.floor((low + high) / 2);\n    if (nums[mid] === target) return mid;\n    else if (nums[mid] < target) low = mid + 1;\n    else high = mid - 1;\n  }\n  return -1;\n}`,
      timeComplexity: 'O(log N)',
      spaceComplexity: 'O(1)',
      pros: 'Logarithmic search time — searches 1,000,000 elements in <= 20 steps.',
      cons: 'Requires array to be sorted.',
    },
    interviewTips: {
      whenToThink: 'Whenever an array is sorted, or you need to find an element/boundary in monotonic search space.',
      commonMistakes: 'Using while(low < high) instead of while(low <= high), missing the 1-element case.',
    },
    patternRecognition: {
      patternName: 'Monotonic Search Space Bisection',
      whyThisPattern: 'Sorted arrays allow discarding half of the search space with a single comparison.',
    },
    optimizationCoach: {
      bottleneck: 'Linear search inspects every element one by one.',
      optimizationIdea: 'Comparing with the middle element immediately rules out 50% of remaining candidates.',
      visualTransition: 'O(N) Linear Scan ➔ Halve Search Space on Each Step ➔ O(log N) Time',
    },
    visualComplexity: {
      type: 'logarithmic-halving',
      stepsExplanation: 'N -> N/2 -> N/4 -> ... -> 1. Maximum steps is log₂ N.',
    },
    learningSteps: [
      { step: 1, text: 'Search space: low = 0, high = 5. mid = 2 (value 3). Target is 9.' },
      { step: 2, text: 'nums[mid] (3) < 9. Target must be in right half -> low becomes mid + 1 = 3.' },
      { step: 3, text: 'Search space: low = 3, high = 5. mid = 4 (value 9).' },
      { step: 4, text: 'nums[4] === 9! Exact match found.' },
      { step: 5, text: 'Return index 4 in only 2 comparisons.' },
    ],
  },
  // 6. SORTING
  {
    id: 'merge-sort',
    title: 'Merge Sort',
    category: 'sorting',
    difficulty: 'Medium',
    tags: ['Array', 'Divide and Conquer', 'Sorting'],
    problemStatement: {
      description: 'Given an array of integers nums, sort the array in ascending order using the Merge Sort algorithm and return it.',
      exampleInput: 'nums = [5, 2, 3, 1]',
      exampleOutput: '[1, 2, 3, 5]',
      constraints: '1 <= nums.length <= 5 * 10^4\n-5 * 10^4 <= nums[i] <= 5 * 10^4',
    },
    bruteForce: {
      explanation: 'Bubble Sort or Insertion Sort compares adjacent items repeatedly in quadratic time.',
      code: `function bubbleSort(nums) {\n  const arr = [...nums];\n  for (let i = 0; i < arr.length; i++) {\n    for (let j = 0; j < arr.length - i - 1; j++) {\n      if (arr[j] > arr[j+1]) {\n        [arr[j], arr[j+1]] = [arr[j+1], arr[j]];\n      }\n    }\n  }\n  return arr;\n}`,
      timeComplexity: 'O(N²)',
      spaceComplexity: 'O(1)',
      pros: 'In-place sorting.',
      cons: 'Too slow for large arrays.',
    },
    optimalSolution: {
      explanation: 'Divide the array into two halves recursively until base arrays of length 1 are reached, then merge sorted halves in O(N) time per level.',
      code: `function mergeSort(nums) {\n  if (nums.length <= 1) return nums;\n  const mid = Math.floor(nums.length / 2);\n  const left = mergeSort(nums.slice(0, mid));\n  const right = mergeSort(nums.slice(mid));\n  return merge(left, right);\n}\nfunction merge(left, right) {\n  const res = [];\n  let i = 0, j = 0;\n  while (i < left.length && j < right.length) {\n    if (left[i] <= right[j]) res.push(left[i++]);\n    else res.push(right[j++]);\n  }\n  return res.concat(left.slice(i)).concat(right.slice(j));\n}`,
      timeComplexity: 'O(N log N)',
      spaceComplexity: 'O(N)',
      pros: 'Guaranteed O(N log N) best, average, and worst time complexity. Stable sort.',
      cons: 'Requires O(N) auxiliary space for merging arrays.',
    },
    interviewTips: {
      whenToThink: 'When stable sorting or guaranteed O(N log N) worst-case time is required (e.g. linked list sorting).',
      commonMistakes: 'Forgetting base case if (nums.length <= 1) return nums.',
    },
    patternRecognition: {
      patternName: 'Divide and Conquer',
      whyThisPattern: 'Sorting two already-sorted halves takes linear time O(N). Splitting takes O(log N) depth.',
    },
    optimizationCoach: {
      bottleneck: 'Quadratic sorts compare elements that are far out of order multiple times.',
      optimizationIdea: 'Split problem in half recursively and merge sorted results in linear time.',
      visualTransition: 'O(N²) Adjacent Swaps ➔ O(log N) Splitting + O(N) Merging ➔ O(N log N) Total',
    },
    visualComplexity: {
      type: 'recurrence-tree',
      stepsExplanation: 'Tree depth is log₂ N. At each of the log N levels, exactly N elements are merged.',
    },
    learningSteps: [
      { step: 1, text: 'Split [5, 2, 3, 1] into [5, 2] and [3, 1].' },
      { step: 2, text: 'Split [5, 2] into [5] and [2]. Merge into sorted [2, 5].' },
      { step: 3, text: 'Split [3, 1] into [3] and [1]. Merge into sorted [1, 3].' },
      { step: 4, text: 'Merge sorted halves [2, 5] and [1, 3] linearly: pick 1, then 2, then 3, then 5.' },
      { step: 5, text: 'Final sorted array [1, 2, 3, 5] produced in O(N log N) time.' },
    ],
  },
  // 7. LINKED LISTS
  {
    id: 'reverse-linked-list',
    title: 'Reverse Linked List',
    category: 'linked-lists',
    difficulty: 'Easy',
    tags: ['Linked List', 'Recursion'],
    problemStatement: {
      description: 'Given the head of a singly linked list, reverse the list, and return the reversed list head.',
      exampleInput: 'head = [1, 2, 3, 4, 5]',
      exampleOutput: '[5, 4, 3, 2, 1]',
      constraints: 'The number of nodes in the list is the range [0, 5000].\n-5000 <= Node.val <= 5000',
    },
    bruteForce: {
      explanation: 'Copy all node values into an array, reverse the array, and overwrite node values.',
      code: `function reverseListBrute(head) {\n  const vals = [];\n  let curr = head;\n  while (curr) { vals.push(curr.val); curr = curr.next; }\n  vals.reverse();\n  curr = head;\n  for (const v of vals) { curr.val = v; curr = curr.next; }\n  return head;\n}`,
      timeComplexity: 'O(N)',
      spaceComplexity: 'O(N)',
      pros: 'Simple if array manipulation is allowed.',
      cons: 'Uses O(N) extra space and copies data rather than changing pointers.',
    },
    optimalSolution: {
      explanation: 'Iteratively change next pointers in place using three pointers: prev, curr, and nextTemp.',
      code: `function reverseListOptimal(head) {\n  let prev = null;\n  let curr = head;\n  while (curr !== null) {\n    const nextTemp = curr.next;\n    curr.next = prev;\n    prev = curr;\n    curr = nextTemp;\n  }\n  return prev;\n}`,
      timeComplexity: 'O(N)',
      spaceComplexity: 'O(1)',
      pros: 'In-place pointer reversal with O(1) memory.',
      cons: 'Must save curr.next in a temp variable before overwriting.',
    },
    interviewTips: {
      whenToThink: 'Whenever reversing nodes, checking palindromes, or manipulating linked list pointers.',
      commonMistakes: 'Losing the reference to curr.next before setting curr.next = prev.',
    },
    patternRecognition: {
      patternName: 'In-Place Pointer Reversal',
      whyThisPattern: 'Linked lists allow O(1) structural re-wiring without moving payload data in memory.',
    },
    optimizationCoach: {
      bottleneck: 'Copying node values to an array wastes O(N) memory.',
      optimizationIdea: 'Simply reverse the direction of the .next arrow on each node as you traverse.',
      visualTransition: 'O(N) Array Copying ➔ 3-Pointer In-Place Reversal ➔ O(1) Space',
    },
    visualComplexity: {
      type: 'linear-scan',
      stepsExplanation: 'We visit each of the N nodes exactly once, performing 3 pointer reassignments.',
    },
    learningSteps: [
      { step: 1, text: 'Initialize prev = null, curr = node(1).' },
      { step: 2, text: 'Save nextTemp = node(2). Point node(1).next to prev (null).' },
      { step: 3, text: 'Advance prev = node(1), curr = node(2).' },
      { step: 4, text: 'Repeat until curr reaches null; prev points to new head node(5).' },
      { step: 5, text: 'Return prev as reversed list head.' },
    ],
  },
  // 8. STACKS
  {
    id: 'valid-parentheses',
    title: 'Valid Parentheses',
    category: 'stacks',
    difficulty: 'Easy',
    tags: ['String', 'Stack'],
    problemStatement: {
      description: 'Given a string s containing just the characters "(", ")", "{", "}", "[" and "]", determine if the input string is valid. Open brackets must be closed by the same type of brackets in the correct order.',
      exampleInput: 's = "()[]{}"',
      exampleOutput: 'true',
      constraints: '1 <= s.length <= 10^4\ns consists of parentheses only "()[]{}"',
    },
    bruteForce: {
      explanation: 'Repeatedly replace matching pairs "()", "[]", "{}" with empty strings until no more replacements can be made.',
      code: `function isValidBrute(s) {\n  let prevLength = -1;\n  while (s.length !== prevLength) {\n    prevLength = s.length;\n    s = s.replace('()', '').replace('[]', '').replace('{}', '');\n  }\n  return s.length === 0;\n}`,
      timeComplexity: 'O(N²)',
      spaceComplexity: 'O(N)',
      pros: 'Easy to conceptualize string reduction.',
      cons: 'String replacement creates new strings repeatedly, taking O(N²) time.',
    },
    optimalSolution: {
      explanation: 'Use a Stack. Push opening brackets onto the stack. For closing brackets, check if the top of the stack has the matching opening bracket.',
      code: `function isValidOptimal(s) {\n  const stack = [];\n  const map = { ')': '(', '}': '{', ']': '[' };\n  for (let char of s) {\n    if (!map[char]) {\n      stack.push(char);\n    } else {\n      const top = stack.pop();\n      if (top !== map[char]) return false;\n    }\n  }\n  return stack.length === 0;\n}`,
      timeComplexity: 'O(N)',
      spaceComplexity: 'O(N)',
      pros: 'Single linear pass with O(1) stack push and pop operations.',
      cons: 'Requires O(N) space for the stack in the worst case (e.g. "(((((").',
    },
    interviewTips: {
      whenToThink: 'When matching nested structures, balancing symbols, or parsing expressions.',
      commonMistakes: 'Forgetting to check if stack.length === 0 at the end.',
    },
    patternRecognition: {
      patternName: 'LIFO Stack Matching',
      whyThisPattern: 'The most recently opened bracket must be the first one to close (Last-In, First-Out).',
    },
    optimizationCoach: {
      bottleneck: 'Repeated string replace scans the entire string over and over.',
      optimizationIdea: 'Use a Stack so each character is pushed once and popped once in O(1) time.',
      visualTransition: 'O(N²) String Replacement ➔ LIFO Stack Push/Pop ➔ O(N) Linear Time',
    },
    visualComplexity: {
      type: 'stack-operations',
      stepsExplanation: 'Every character undergoes at most 1 push and 1 pop. O(N) total work.',
    },
    learningSteps: [
      { step: 1, text: 'Char "(" is an opener -> push onto stack: ["("].' },
      { step: 2, text: 'Char ")" is a closer -> pop stack top "(". Matches! Stack is now [].' },
      { step: 3, text: 'Char "[" -> push: ["["]. Char "]" -> pop and match.' },
      { step: 4, text: 'Char "{" -> push: ["{"]. Char "}" -> pop and match.' },
      { step: 5, text: 'End of string reached and stack is empty. Return true.' },
    ],
  },
  // 9. DYNAMIC PROGRAMMING
  {
    id: 'climbing-stairs',
    title: 'Climbing Stairs',
    category: 'dp',
    difficulty: 'Easy',
    tags: ['Math', 'Dynamic Programming', 'Memoization'],
    problemStatement: {
      description: 'You are climbing a staircase. It takes n steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?',
      exampleInput: 'n = 3',
      exampleOutput: '3 (1+1+1, 1+2, 2+1)',
      constraints: '1 <= n <= 45',
    },
    bruteForce: {
      explanation: 'Use pure recursion: climbStairs(n) = climbStairs(n-1) + climbStairs(n-2).',
      code: `function climbStairsBrute(n) {\n  if (n <= 2) return n;\n  return climbStairsBrute(n - 1) + climbStairsBrute(n - 2);\n}`,
      timeComplexity: 'O(2^N)',
      spaceComplexity: 'O(N)',
      pros: 'Direct mathematical recurrence.',
      cons: 'Exponential time due to recomputing overlapping subproblems.',
    },
    optimalSolution: {
      explanation: 'Notice this is the Fibonacci sequence. Use two variables to store the previous two results in O(1) space.',
      code: `function climbStairsOptimal(n) {\n  if (n <= 2) return n;\n  let prev2 = 1, prev1 = 2;\n  for (let i = 3; i <= n; i++) {\n    const curr = prev1 + prev2;\n    prev2 = prev1;\n    prev1 = curr;\n  }\n  return prev1;\n}`,
      timeComplexity: 'O(N)',
      spaceComplexity: 'O(1)',
      pros: 'Optimal linear time and O(1) space.',
      cons: 'Requires identifying overlapping substructure.',
    },
    interviewTips: {
      whenToThink: 'When counting distinct ways to reach a state where current choice depends on immediate prior choices.',
      commonMistakes: 'Off-by-one errors in loop bounds.',
    },
    patternRecognition: {
      patternName: '1D Dynamic Programming / Fibonacci',
      whyThisPattern: 'To reach step i, you could only have come from step i-1 (1 step) or step i-2 (2 steps).',
    },
    optimizationCoach: {
      bottleneck: 'Exponential recursion calculates climbStairs(n-2) multiple times across branches.',
      optimizationIdea: 'Store the last two step counts and iteratively compute the next step in O(1) time.',
      visualTransition: 'O(2^N) Exponential Tree ➔ Tabulation / Memoization ➔ O(N) Linear Time',
    },
    visualComplexity: {
      type: 'dp-subproblems',
      stepsExplanation: 'We eliminate exponential branch recursion by solving N unique subproblems once.',
    },
    learningSteps: [
      { step: 1, text: 'Base cases: 1 way to climb 1 step, 2 ways to climb 2 steps.' },
      { step: 2, text: 'Step 3: ways(3) = ways(2) + ways(1) = 2 + 1 = 3.' },
      { step: 3, text: 'Step 4: ways(4) = ways(3) + ways(2) = 3 + 2 = 5.' },
      { step: 4, text: 'Step 5: ways(5) = ways(4) + ways(3) = 5 + 3 = 8.' },
      { step: 5, text: 'Iterate up to n in linear time.' },
    ],
  },
  // 10. GRAPHS
  {
    id: 'number-of-islands',
    title: 'Number of Islands',
    category: 'graphs',
    difficulty: 'Medium',
    tags: ['Array', 'Depth-First Search', 'Breadth-First Search', 'Matrix'],
    problemStatement: {
      description: 'Given an m x n 2D binary grid grid which represents a map of "1"s (land) and "0"s (water), return the number of islands. An island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically.',
      exampleInput: 'grid = [["1","1","0","0","0"],["1","1","0","0","0"],["0","0","1","0","0"],["0","0","0","1","1"]]',
      exampleOutput: '3',
      constraints: 'm == grid.length\nn == grid[i].length\n1 <= m, n <= 300\ngrid[i][j] is "0" or "1".',
    },
    bruteForce: {
      explanation: 'Without marking visited cells, searching would cycle infinitely. A basic approach uses a separate visited matrix of size M x N.',
      code: `function numIslandsWithVisited(grid) {\n  let count = 0;\n  const m = grid.length, n = grid[0].length;\n  const vis = Array.from({ length: m }, () => Array(n).fill(false));\n  function dfs(r, c) {\n    if (r<0 || c<0 || r>=m || c>=n || grid[r][c]==='0' || vis[r][c]) return;\n    vis[r][c] = true;\n    dfs(r+1,c); dfs(r-1,c); dfs(r,c+1); dfs(r,c-1);\n  }\n  for (let r=0; r<m; r++) {\n    for (let c=0; c<n; c++) {\n      if (grid[r][c]==='1' && !vis[r][c]) {\n        count++; dfs(r, c);\n      }\n    }\n  }\n  return count;\n}`,
      timeComplexity: 'O(M × N)',
      spaceComplexity: 'O(M × N)',
      pros: 'Does not mutate input grid.',
      cons: 'Wastes O(M × N) memory for the visited boolean matrix.',
    },
    optimalSolution: {
      explanation: 'When a "1" is encountered, increment island count and use DFS/BFS to sink the island by mutating connected "1"s into "0"s.',
      code: `function numIslandsOptimal(grid) {\n  let count = 0;\n  const m = grid.length, n = grid[0].length;\n  function sink(r, c) {\n    if (r<0 || c<0 || r>=m || c>=n || grid[r][c]==='0') return;\n    grid[r][c] = '0'; // sink land\n    sink(r+1, c); sink(r-1, c); sink(r, c+1); sink(r, c-1);\n  }\n  for (let r=0; r<m; r++) {\n    for (let c=0; c<n; c++) {\n      if (grid[r][c] === '1') {\n        count++;\n        sink(r, c);\n      }\n    }\n  }\n  return count;\n}`,
      timeComplexity: 'O(M × N)',
      spaceComplexity: 'O(min(M, N))',
      pros: 'No extra visited matrix required. Space bounded by recursion depth.',
      cons: 'Mutates input grid (can restore after if needed).',
    },
    interviewTips: {
      whenToThink: 'Whenever counting connected components in a grid or graph.',
      commonMistakes: 'Forgetting boundary checks r<0 || c<0 || r>=m || c>=n.',
    },
    patternRecognition: {
      patternName: 'Connected Components / Grid DFS Flood Fill',
      whyThisPattern: 'Traversing all 4-direction neighbors from any unvisited land cell visits its entire island component.',
    },
    optimizationCoach: {
      bottleneck: 'Allocating an M x N boolean visited array increases memory usage.',
      optimizationIdea: 'In-place flood fill: mark visited land cells as water ("0") so they are never revisited.',
      visualTransition: 'O(M×N) Visited Matrix ➔ In-Place Flood Fill Sink ➔ O(1) Auxiliary Space',
    },
    visualComplexity: {
      type: 'grid-traversal',
      stepsExplanation: 'Every cell in the M x N grid is visited a constant number of times (once in outer loop, at most 4 times by neighbor DFS).',
    },
    learningSteps: [
      { step: 1, text: 'Scan grid left-to-right, top-to-bottom until finding first "1" at (0, 0).' },
      { step: 2, text: 'Island #1 discovered! Increment count = 1. Launch DFS flood fill.' },
      { step: 3, text: 'DFS visits all connected "1"s in upper-left and sinks them to "0".' },
      { step: 4, text: 'Continue scanning until finding unvisited "1" at (2, 2) -> Island #2.' },
      { step: 5, text: 'Find last island at bottom-right (3, 3) -> total islands = 3.' },
    ],
  },
  {
    id: 'kmp-string-matching',
    title: 'KMP String Matching Algorithm',
    category: 'strings',
    difficulty: 'Hard',
    tags: ['String', 'KMP', 'Pattern Matching', 'LPS Array'],
    problemStatement: {
      description: 'Given a text string and a pattern string, return the index of the first occurrence of pattern in text using the Knuth-Morris-Pratt (KMP) linear O(N+M) time algorithm.',
      exampleInput: 'text = "ABABDABACDABABCABAB", pattern = "ABABCABAB"',
      exampleOutput: '10',
      constraints: '1 <= text.length, pattern.length <= 10^5',
    },
    bruteForce: {
      explanation: 'Check pattern against text starting at every character index i. Reset text index back to i+1 upon mismatch.',
      code: `function kmpBrute(text, pattern) {\n  for (let i = 0; i <= text.length - pattern.length; i++) {\n    let j = 0;\n    while (j < pattern.length && text[i + j] === pattern[j]) j++;\n    if (j === pattern.length) return i;\n  }\n  return -1;\n}`,
      timeComplexity: 'O(N × M)',
      spaceComplexity: 'O(1)',
      pros: 'Simple double loop.',
      cons: 'Repeatedly re-scans text characters after mismatches.',
    },
    optimalSolution: {
      explanation: 'Precompute the Longest Proper Prefix which is also Suffix (LPS) array for pattern. Use LPS to skip redundant comparisons when mismatch occurs.',
      code: `function kmpOptimal(text, pattern) {\n  const lps = new Array(pattern.length).fill(0);\n  let len = 0, i = 1;\n  while (i < pattern.length) {\n    if (pattern[i] === pattern[len]) lps[i++] = ++len;\n    else if (len !== 0) len = lps[len - 1];\n    else lps[i++] = 0;\n  }\n  let t = 0, p = 0;\n  while (t < text.length) {\n    if (text[t] === pattern[p]) { t++; p++; }\n    if (p === pattern.length) return t - p;\n    else if (t < text.length && text[t] !== pattern[p]) {\n      if (p !== 0) p = lps[p - 1];\n      else t++;\n    }\n  }\n  return -1;\n}`,
      timeComplexity: 'O(N + M)',
      spaceComplexity: 'O(M)',
      pros: 'Never backtracks text index t.',
      cons: 'Requires understanding LPS prefix-suffix array preprocessing.',
    },
    interviewTips: {
      whenToThink: 'Whenever asked for exact string matching in linear O(N) time without backtracking.',
      commonMistakes: 'Forgetting to handle p = lps[p - 1] fallback correctly.',
    },
    patternRecognition: {
      patternName: 'Prefix Function (LPS) / Automata',
      whyThisPattern: 'LPS stores how many characters can be reused after a mismatch.',
    },
    optimizationCoach: {
      bottleneck: 'Brute force backtracks text pointer t to i+1 on mismatch.',
      optimizationIdea: 'Build LPS table to skip matching prefix characters automatically.',
      visualTransition: 'O(N × M) Re-scanning ➔ LPS Table Skip ➔ O(N + M) KMP Linear Scan',
    },
    visualComplexity: {
      type: 'linear-scan',
      stepsExplanation: 'Text index t only moves forward. Pattern index p drops according to LPS array.',
    },
    learningSteps: [
      { step: 1, text: 'Compute LPS array for pattern "ABABCABAB" -> [0, 0, 1, 2, 0, 1, 2, 3, 4].' },
      { step: 2, text: 'Scan text from index 0. Match "ABABC" up to index 4.' },
      { step: 3, text: 'Mismatch at index 5. Fallback p to lps[4-1] = lps[3] = 2 ("AB").' },
      { step: 4, text: 'Resume matching without rewinding text index t.' },
      { step: 5, text: 'Pattern fully matched at text index 10. Return 10.' },
    ],
  },
  {
    id: 'sliding-window-maximum',
    title: 'Sliding Window Maximum',
    category: 'queues',
    difficulty: 'Hard',
    tags: ['Array', 'Queue', 'Monotonic Deque', 'Sliding Window'],
    problemStatement: {
      description: 'Given an array nums and a sliding window of size k moving from left to right, return the max element in each sliding window.',
      exampleInput: 'nums = [1,3,-1,-3,5,3,6,7], k = 3',
      exampleOutput: '[3,3,5,5,6,7]',
      constraints: '1 <= nums.length <= 10^5, 1 <= k <= nums.length',
    },
    bruteForce: {
      explanation: 'Find maximum element in every k-length subsegment independently.',
      code: `function maxSlidingWindowBrute(nums, k) {\n  const result = [];\n  for (let i = 0; i <= nums.length - k; i++) {\n    let maxVal = -Infinity;\n    for (let j = i; j < i + k; j++) maxVal = Math.max(maxVal, nums[j]);\n    result.push(maxVal);\n  }\n  return result;\n}`,
      timeComplexity: 'O(N × K)',
      spaceComplexity: 'O(1)',
      pros: 'Simple to implement.',
      cons: 'Slow quadratic scaling when K is large.',
    },
    optimalSolution: {
      explanation: 'Maintain a Monotonic Decreasing Deque storing element indices. Front of deque always holds maximum index for current window.',
      code: `function maxSlidingWindowOptimal(nums, k) {\n  const deque = []; // stores indices\n  const result = [];\n  for (let i = 0; i < nums.length; i++) {\n    if (deque.length > 0 && deque[0] <= i - k) deque.shift();\n    while (deque.length > 0 && nums[deque[deque.length - 1]] <= nums[i]) {\n      deque.pop();\n    }\n    deque.push(i);\n    if (i >= k - 1) result.push(nums[deque[0]]);\n  }\n  return result;\n}`,
      timeComplexity: 'O(N)',
      spaceComplexity: 'O(K)',
      pros: 'Single linear pass. Each index pushed and popped from deque at most once.',
      cons: 'Requires understanding monotonic queue invariant.',
    },
    interviewTips: {
      whenToThink: 'Whenever finding dynamic maximum or minimum in moving contiguous window.',
      commonMistakes: 'Storing values instead of indices in deque, which prevents checking out-of-window bounds.',
    },
    patternRecognition: {
      patternName: 'Monotonic Queue / Monotonic Deque',
      whyThisPattern: 'Elements smaller than current incoming element will never be window maximum in future.',
    },
    optimizationCoach: {
      bottleneck: 'Brute force scans K elements repeatedly for N windows.',
      optimizationIdea: 'Use Monotonic Deque to keep candidate maximums in decreasing order.',
      visualTransition: 'O(N × K) Window Scans ➔ Monotonic Deque ➔ O(N) Linear Time',
    },
    visualComplexity: {
      type: 'linear-scan',
      stepsExplanation: 'Every array element enters and exits deque at most once across total execution.',
    },
    learningSteps: [
      { step: 1, text: 'Initialize empty deque. Process nums[0]=1, deque=[0].' },
      { step: 2, text: 'Process nums[1]=3. 3 > 1, pop 0, deque=[1].' },
      { step: 3, text: 'Process nums[2]=-1. deque=[1, 2]. Window [1,3,-1] max = nums[deque[0]] = 3.' },
      { step: 4, text: 'Process nums[4]=5. 5 > -3 and 5 > 3. Clear deque, deque=[4]. Window max = 5.' },
      { step: 5, text: 'Return result array [3, 3, 5, 5, 6, 7].' },
    ],
  },
  {
    id: 'sieve-of-eratosthenes',
    title: 'Sieve of Eratosthenes',
    category: 'math',
    difficulty: 'Medium',
    tags: ['Math', 'Number Theory', 'Sieve', 'Primes'],
    problemStatement: {
      description: 'Given an integer n, return the number of prime numbers strictly less than n.',
      exampleInput: 'n = 10',
      exampleOutput: '4 (primes 2, 3, 5, 7)',
      constraints: '0 <= n <= 5 * 10^6',
    },
    bruteForce: {
      explanation: 'Check if each number from 2 to n-1 is prime using trial division up to sqrt(i).',
      code: `function countPrimesBrute(n) {\n  let count = 0;\n  for (let i = 2; i < n; i++) {\n    let isPrime = true;\n    for (let j = 2; j * j <= i; j++) {\n      if (i % j === 0) { isPrime = false; break; }\n    }\n    if (isPrime) count++;\n  }\n  return count;\n}`,
      timeComplexity: 'O(N √N)',
      spaceComplexity: 'O(1)',
      pros: 'No extra memory required.',
      cons: 'Slow for N > 10^5.',
    },
    optimalSolution: {
      explanation: 'Sieve of Eratosthenes: Create boolean array isPrime initialized to true. Mark multiples of each prime starting from i*i as false.',
      code: `function countPrimesOptimal(n) {\n  if (n <= 2) return 0;\n  const isPrime = new Array(n).fill(true);\n  isPrime[0] = isPrime[1] = false;\n  for (let i = 2; i * i < n; i++) {\n    if (isPrime[i]) {\n      for (let j = i * i; j < n; j += i) {\n        isPrime[j] = false;\n      }\n    }\n  }\n  return isPrime.reduce((acc, val) => acc + (val ? 1 : 0), 0);\n}`,
      timeComplexity: 'O(N log log N)',
      spaceComplexity: 'O(N)',
      pros: 'Near-linear O(N log log N) execution time.',
      cons: 'Requires O(N) boolean array space.',
    },
    interviewTips: {
      whenToThink: 'Whenever generating prime numbers or precomputing prime factors up to N.',
      commonMistakes: 'Starting composite loop at 2*i instead of i*i (which avoids re-marking smaller multiples).',
    },
    patternRecognition: {
      patternName: 'Prime Sieve / Precomputation',
      whyThisPattern: 'Marking multiples eliminates testing composite numbers repeatedly.',
    },
    optimizationCoach: {
      bottleneck: 'Trial division tests divisibility on numbers repeatedly.',
      optimizationIdea: 'Mark all multiples of known primes directly in boolean array.',
      visualTransition: 'O(N √N) Trial Division ➔ Sieve Multiple Elimination ➔ O(N log log N) Sieve',
    },
    visualComplexity: {
      type: 'linear-scan',
      stepsExplanation: 'Sum of N/p over primes p yields harmonic series bound O(N log log N).',
    },
    learningSteps: [
      { step: 1, text: 'Initialize boolean array isPrime of size 10 to true. Mark 0 and 1 false.' },
      { step: 2, text: 'i = 2 is prime. Mark multiples 4, 6, 8 false.' },
      { step: 3, text: 'i = 3 is prime. Mark multiple 9 false.' },
      { step: 4, text: 'Remaining true indices: 2, 3, 5, 7.' },
      { step: 5, text: 'Return count = 4.' },
    ],
  },
  {
    id: 'segment-tree-rmq',
    title: 'Segment Tree (Range Minimum Query)',
    category: 'trees',
    difficulty: 'Hard',
    tags: ['Tree', 'Segment Tree', 'Range Query', 'Binary Tree'],
    problemStatement: {
      description: 'Build a Segment Tree over an array to answer Range Minimum Queries (RMQ) in O(log N) time and perform point updates in O(log N) time.',
      exampleInput: 'nums = [1, 3, 5, 7, 9, 11], queryRange = [1, 4]',
      exampleOutput: '3 (minimum in range [3, 5, 7, 9])',
      constraints: '1 <= nums.length <= 10^5',
    },
    bruteForce: {
      explanation: 'Scan subarray from L to R linearly for every query.',
      code: `function rmqBrute(nums, L, R) {\n  let minVal = Infinity;\n  for (let i = L; i <= R; i++) minVal = Math.min(minVal, nums[i]);\n  return minVal;\n}`,
      timeComplexity: 'O(N) per query',
      spaceComplexity: 'O(1)',
      pros: 'No tree construction required.',
      cons: 'Slow O(N) query response time for Q queries.',
    },
    optimalSolution: {
      explanation: 'Build a 4N array tree where each node stores the minimum of its children range. Answer queries by combining tree node ranges.',
      code: `function buildSegmentTree(nums) {\n  const n = nums.length;\n  const tree = new Array(4 * n).fill(Infinity);\n  function build(node, start, end) {\n    if (start === end) { tree[node] = nums[start]; return; }\n    const mid = Math.floor((start + end) / 2);\n    build(2 * node, start, mid);\n    build(2 * node + 1, mid + 1, end);\n    tree[node] = Math.min(tree[2 * node], tree[2 * node + 1]);\n  }\n  build(1, 0, n - 1);\n  function query(node, start, end, l, r) {\n    if (r < start || end < l) return Infinity;\n    if (l <= start && end <= r) return tree[node];\n    const mid = Math.floor((start + end) / 2);\n    return Math.min(query(2 * node, start, mid, l, r), query(2 * node + 1, mid + 1, end, l, r));\n  }\n  return { query: (l, r) => query(1, 0, n - 1, l, r) };\n}`,
      timeComplexity: 'O(N) build, O(log N) query/update',
      spaceComplexity: 'O(N)',
      pros: 'Logarithmic query and update times.',
      cons: 'Requires 4N tree space and recursive range logic.',
    },
    interviewTips: {
      whenToThink: 'Whenever dynamic array range queries and frequent point/range updates occur together.',
      commonMistakes: 'Incorrect mid boundary logic causing infinite recursion.',
    },
    patternRecognition: {
      patternName: 'Segment Tree / Divide and Conquer Tree',
      whyThisPattern: 'Subsegment bounds map directly to tree node interval ranges.',
    },
    optimizationCoach: {
      bottleneck: 'Scanning subarray linearly takes O(N) time for every query.',
      optimizationIdea: 'Precompute range minimums in a full binary segment tree.',
      visualTransition: 'O(N) Linear Range Scan ➔ Segment Tree Nodes ➔ O(log N) Range Query',
    },
    visualComplexity: {
      type: 'tree-traversal',
      stepsExplanation: 'At most 4 * log(N) tree nodes visited per range query.',
    },
    learningSteps: [
      { step: 1, text: 'Build segment tree leaves from nums [1, 3, 5, 7, 9, 11].' },
      { step: 2, text: 'Compute internal node minimums: min(1,3)=1, min(5,7)=5, min(9,11)=9.' },
      { step: 3, text: 'Execute queryRange(1, 4) for indices [3, 5, 7, 9].' },
      { step: 4, text: 'Segment tree combines range nodes [1..1] (val 3) and [2..3] (val 5) and [4..4] (val 9).' },
      { step: 5, text: 'Return min(3, 5, 9) = 3 in O(log N) operations.' },
    ],
  },
  {
    id: 'subsets-bitmask',
    title: 'Subsets using Bitmasking',
    category: 'bit-manipulation',
    difficulty: 'Medium',
    tags: ['Array', 'Bit Manipulation', 'Bitmask', 'Powerset'],
    problemStatement: {
      description: 'Given an integer array nums of unique elements, return all possible subsets (the power set) using bitmask enumeration.',
      exampleInput: 'nums = [1, 2, 3]',
      exampleOutput: '[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]',
      constraints: '1 <= nums.length <= 10',
    },
    bruteForce: {
      explanation: 'Use recursive backtracking to decide whether to include or exclude each element.',
      code: `function subsetsRecursive(nums) {\n  const res = [];\n  function backtrack(index, path) {\n    if (index === nums.length) { res.push([...path]); return; }\n    path.push(nums[index]);\n    backtrack(index + 1, path);\n    path.pop();\n    backtrack(index + 1, path);\n  }\n  backtrack(0, []);\n  return res;\n}`,
      timeComplexity: 'O(N × 2^N)',
      spaceComplexity: 'O(N)',
      pros: 'Standard backtracking approach.',
      cons: 'Uses recursion call stack memory.',
    },
    optimalSolution: {
      explanation: 'Iterate integer mask from 0 to (1<<N)-1. If the k-th bit of mask is set, include nums[k] in the subset.',
      code: `function subsetsBitmask(nums) {\n  const n = nums.length;\n  const total = 1 << n;\n  const result = [];\n  for (let mask = 0; mask < total; mask++) {\n    const subset = [];\n    for (let i = 0; i < n; i++) {\n      if ((mask & (1 << i)) !== 0) {\n        subset.push(nums[i]);\n      }\n    }\n    result.push(subset);\n  }\n  return result;\n}`,
      timeComplexity: 'O(N × 2^N)',
      spaceComplexity: 'O(1) auxiliary space',
      pros: 'Non-recursive iterative state generation with zero call stack overhead.',
      cons: 'Bounded to N <= 30 because of 32-bit integer shift limit.',
    },
    interviewTips: {
      whenToThink: 'Whenever generating powerset subsets or state combinations when N <= 20.',
      commonMistakes: 'Forgetting parenthesization in (mask & (1 << i)) !== 0 due to operator precedence.',
    },
    patternRecognition: {
      patternName: 'Bitmask Powerset Enumeration',
      whyThisPattern: 'Binary bits 0 and 1 correspond to exclude/include subset states.',
    },
    optimizationCoach: {
      bottleneck: 'Recursive backtracking uses call stack frames.',
      optimizationIdea: 'Use binary integers from 0 to 2^N - 1 as bit vectors representing subsets.',
      visualTransition: 'Recursive Backtracking Call Stack ➔ Bitmask Loop ➔ Non-recursive O(2^N)',
    },
    visualComplexity: {
      type: 'linear-scan',
      stepsExplanation: 'Loops mask from 0 to 2^N - 1. Checks N bits per mask.',
    },
    learningSteps: [
      { step: 1, text: 'Array nums = [1, 2, 3], length N = 3. Total subsets = 1<<3 = 8.' },
      { step: 2, text: 'mask = 000_2 (0) -> subset []' },
      { step: 3, text: 'mask = 001_2 (1) -> bit 0 set -> subset [1]' },
      { step: 4, text: 'mask = 011_2 (3) -> bits 0 and 1 set -> subset [1, 2]' },
      { step: 5, text: 'mask = 111_2 (7) -> bits 0, 1, and 2 set -> subset [1, 2, 3]. Complete!' },
    ],
  },
  {
    id: 'lru-cache',
    title: 'LRU Cache Design',
    category: 'linked-lists',
    difficulty: 'Hard',
    tags: ['Hash Table', 'Linked List', 'Doubly Linked List', 'Design'],
    problemStatement: {
      description: 'Design a data structure that follows the constraints of a Least Recently Used (LRU) cache with O(1) get and put operations.',
      exampleInput: 'LRUCache(2); put(1, 1); put(2, 2); get(1); put(3, 3); get(2);',
      exampleOutput: 'get(1) -> 1, get(2) -> -1 (evicted)',
      constraints: '1 <= capacity <= 3000, 0 <= key, value <= 10^4',
    },
    bruteForce: {
      explanation: 'Use an array of {key, value, timestamp} objects. On access, scan array in O(N) to find key or find oldest timestamp for eviction.',
      code: `function LRUCacheBrute(capacity) {\n  this.capacity = capacity;\n  this.cache = [];\n  this.time = 0;\n  this.get = function(key) {\n    this.time++;\n    const item = this.cache.find(c => c.key === key);\n    if (!item) return -1;\n    item.time = this.time;\n    return item.value;\n  };\n  this.put = function(key, value) {\n    this.time++;\n    const item = this.cache.find(c => c.key === key);\n    if (item) { item.value = value; item.time = this.time; return; }\n    if (this.cache.length >= this.capacity) {\n      this.cache.sort((a, b) => a.time - b.time);\n      this.cache.shift(); // evict oldest\n    }\n    this.cache.push({ key, value, time: this.time });\n  };\n}`,
      timeComplexity: 'O(N) get, O(N log N) put',
      spaceComplexity: 'O(N)',
      pros: 'Simple array storage.',
      cons: 'Slow O(N) array search and sorting on evictions.',
    },
    optimalSolution: {
      explanation: 'Combine a HashMap (O(1) key node lookup) with a Doubly Linked List (O(1) node removal and insertion at head). Head = Most Recent, Tail = Least Recent.',
      code: `class Node {\n  constructor(key, value) {\n    this.key = key;\n    this.value = value;\n    this.prev = null;\n    this.next = null;\n  }\n}\nclass LRUCacheOptimal {\n  constructor(capacity) {\n    this.capacity = capacity;\n    this.map = new Map();\n    this.head = new Node(0, 0); // dummy head\n    this.tail = new Node(0, 0); // dummy tail\n    this.head.next = this.tail;\n    this.tail.prev = this.head;\n  }\n  _remove(node) {\n    node.prev.next = node.next;\n    node.next.prev = node.prev;\n  }\n  _insertHead(node) {\n    node.next = this.head.next;\n    node.prev = this.head;\n    this.head.next.prev = node;\n    this.head.next = node;\n  }\n  get(key) {\n    if (!this.map.has(key)) return -1;\n    const node = this.map.get(key);\n    this._remove(node);\n    this._insertHead(node);\n    return node.value;\n  }\n  put(key, value) {\n    if (this.map.has(key)) {\n      this._remove(this.map.get(key));\n    }\n    const node = new Node(key, value);\n    this.map.set(key, node);\n    this._insertHead(node);\n    if (this.map.size > this.capacity) {\n      const lru = this.tail.prev;\n      this._remove(lru);\n      this.map.delete(lru.key);\n    }\n  }\n}`,
      timeComplexity: 'O(1) get & put',
      spaceComplexity: 'O(Capacity)',
      pros: 'Guaranteed O(1) constant time for all operations.',
      cons: 'Requires pointer management for doubly linked list node updates.',
    },
    interviewTips: {
      whenToThink: 'Whenever designing bounded caches with constant-time eviction policies.',
      commonMistakes: 'Forgetting to remove evicted node key from HashMap or unlinking pointers incorrectly.',
    },
    patternRecognition: {
      patternName: 'Doubly Linked List + HashMap',
      whyThisPattern: 'Map enables O(1) node lookup by key while Doubly Linked List enables O(1) splicing.',
    },
    optimizationCoach: {
      bottleneck: 'Array scanning takes O(N) time to find items or least recently used timestamp.',
      optimizationIdea: 'Pair HashMap with Doubly Linked List for instant O(1) pointer updates.',
      visualTransition: 'O(N) Array Scan ➔ Map + Doubly Linked List ➔ O(1) Constant Time Operations',
    },
    visualComplexity: {
      type: 'pointer-manipulation',
      stepsExplanation: 'Both get and put perform at most 4 pointer rewires and 1 Map lookup.',
    },
    learningSteps: [
      { step: 1, text: 'Initialize LRUCache capacity = 2 with dummy head <-> tail.' },
      { step: 2, text: 'put(1, 1): Add key 1 to map and insert at head [Head <-> 1 <-> Tail].' },
      { step: 3, text: 'put(2, 2): Add key 2. List becomes [Head <-> 2 <-> 1 <-> Tail].' },
      { step: 4, text: 'get(1): Move node 1 to head -> [Head <-> 1 <-> 2 <-> Tail]. Return 1.' },
      { step: 5, text: 'put(3, 3): Capacity exceeded (3 > 2). Evict tail.prev (node 2). Add 3 -> [Head <-> 3 <-> 1 <-> Tail].' },
    ],
  },
  {
    id: 'kth-largest-element',
    title: 'Kth Largest Element in an Array',
    category: 'heaps',
    difficulty: 'Medium',
    tags: ['Array', 'Divide and Conquer', 'Heap', 'Quickselect'],
    problemStatement: {
      description: 'Given an integer array nums and an integer k, return the kth largest element in the array.',
      exampleInput: 'nums = [3, 2, 1, 5, 6, 4], k = 2',
      exampleOutput: '5',
      constraints: '1 <= k <= nums.length <= 10^5',
    },
    bruteForce: {
      explanation: 'Sort the array in descending order and return element at index k - 1.',
      code: `function findKthLargestBrute(nums, k) {\n  nums.sort((a, b) => b - a);\n  return nums[k - 1];\n}`,
      timeComplexity: 'O(N log N)',
      spaceComplexity: 'O(1) or O(N)',
      pros: 'Simple 2-line code.',
      cons: 'Sorts entire array when only k-th element is needed.',
    },
    optimalSolution: {
      explanation: 'Maintain a Min-Heap of size K. For each element, push to heap. If heap size exceeds K, pop the smallest. Top of heap is the Kth largest element.',
      code: `function findKthLargestOptimal(nums, k) {\n  // Min Heap simulation using array\n  const minHeap = [];\n  function pushHeap(val) {\n    minHeap.push(val);\n    minHeap.sort((a, b) => a - b);\n  }\n  for (let num of nums) {\n    pushHeap(num);\n    if (minHeap.length > k) minHeap.shift(); // pop min\n  }\n  return minHeap[0];\n}`,
      timeComplexity: 'O(N log K)',
      spaceComplexity: 'O(K)',
      pros: 'Processes streaming input efficiently with small O(K) space.',
      cons: 'Takes O(N log K) time compared to QuickSelect O(N) average time.',
    },
    interviewTips: {
      whenToThink: 'Whenever finding top K largest/smallest elements in dynamic streams or arrays.',
      commonMistakes: 'Using Max-Heap of size N instead of Min-Heap of size K.',
    },
    patternRecognition: {
      patternName: 'Min-Heap Priority Queue (Top-K)',
      whyThisPattern: 'Keeping heap size bounded at K guarantees smallest element in top K stays at root.',
    },
    optimizationCoach: {
      bottleneck: 'Sorting entire array takes O(N log N) time.',
      optimizationIdea: 'Keep only K largest elements in a Min-Heap.',
      visualTransition: 'O(N log N) Full Sort ➔ Min-Heap of Size K ➔ O(N log K) Linear-Log Time',
    },
    visualComplexity: {
      type: 'linear-scan',
      stepsExplanation: 'Loops N elements. Each heap insertion/eviction takes O(log K) operations.',
    },
    learningSteps: [
      { step: 1, text: 'Initialize empty Min-Heap for K = 2. Input array [3, 2, 1, 5, 6, 4].' },
      { step: 2, text: 'Process 3, 2 -> minHeap = [2, 3].' },
      { step: 3, text: 'Process 1 -> minHeap = [1, 2, 3]. Pop min 1 -> minHeap = [2, 3].' },
      { step: 4, text: 'Process 5, 6 -> minHeap reaches [5, 6] after evicting smaller elements.' },
      { step: 5, text: 'Process 4 -> 4 < minHeap[0] (5), ignore. Top of heap = 5. Return 5.' },
    ],
  },
  {
    id: 'trapping-rain-water',
    title: 'Trapping Rain Water',
    category: 'two-pointers',
    difficulty: 'Hard',
    tags: ['Array', 'Two Pointers', 'Stack', 'Dynamic Programming'],
    problemStatement: {
      description: 'Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.',
      exampleInput: 'height = [0,1,0,2,1,0,1,3,2,1,2,1]',
      exampleOutput: '6 units of water',
      constraints: 'n == height.length, 1 <= n <= 2 * 10^4',
    },
    bruteForce: {
      explanation: 'For each index i, scan left to find leftMax and right to find rightMax. Water trapped at i is min(leftMax, rightMax) - height[i].',
      code: `function trapBrute(height) {\n  let totalWater = 0;\n  for (let i = 0; i < height.length; i++) {\n    let leftMax = 0, rightMax = 0;\n    for (let j = i; j >= 0; j--) leftMax = Math.max(leftMax, height[j]);\n    for (let j = i; j < height.length; j++) rightMax = Math.max(rightMax, height[j]);\n    totalWater += Math.min(leftMax, rightMax) - height[i];\n  }\n  return totalWater;\n}`,
      timeComplexity: 'O(N²)',
      spaceComplexity: 'O(1)',
      pros: 'Simple to understand column water formula.',
      cons: 'Re-scans boundaries repeatedly for every index.',
    },
    optimalSolution: {
      explanation: 'Use Two Pointers (left and right) moving inward. Maintain running leftMax and rightMax. Calculate trapped water at pointer with smaller maximum.',
      code: `function trapOptimal(height) {\n  let left = 0, right = height.length - 1;\n  let leftMax = 0, rightMax = 0;\n  let totalWater = 0;\n  while (left < right) {\n    if (height[left] < height[right]) {\n      if (height[left] >= leftMax) leftMax = height[left];\n      else totalWater += leftMax - height[left];\n      left++;\n    } else {\n      if (height[right] >= rightMax) rightMax = height[right];\n      else totalWater += rightMax - height[right];\n      right--;\n    }\n  }\n  return totalWater;\n}`,
      timeComplexity: 'O(N)',
      spaceComplexity: 'O(1)',
      pros: 'Optimal single linear scan with zero extra auxiliary memory.',
      cons: 'Requires grasping boundary convergence invariant.',
    },
    interviewTips: {
      whenToThink: 'Whenever trapped boundary volume depends on minimum of left and right maximums.',
      commonMistakes: 'Not updating leftMax/rightMax before computing trapped volume difference.',
    },
    patternRecognition: {
      patternName: 'Two Pointers Converging Boundary Scan',
      whyThisPattern: 'The pointer with smaller height bounds the max possible water column.',
    },
    optimizationCoach: {
      bottleneck: 'Brute force scans left and right array bounds repeatedly for every column.',
      optimizationIdea: 'Track running leftMax and rightMax with convergent left and right pointers.',
      visualTransition: 'O(N²) Boundary Scanning ➔ Two Pointers Inward Convergence ➔ O(N) Linear Time',
    },
    visualComplexity: {
      type: 'linear-scan',
      stepsExplanation: 'Pointers left and right meet in middle in exactly N steps.',
    },
    learningSteps: [
      { step: 1, text: 'Initialize left = 0, right = 11, leftMax = 0, rightMax = 0, totalWater = 0.' },
      { step: 2, text: 'left=0 (val 0) < right=11 (val 1). leftMax becomes 0. Move left to 1.' },
      { step: 3, text: 'At index 2 (val 0): leftMax = 1. Water trapped = 1 - 0 = 1.' },
      { step: 4, text: 'At index 5 (val 0): leftMax = 2. Water trapped = 2 - 0 = 2.' },
      { step: 5, text: 'Summing trapped water across all columns yields 6 units.' },
    ],
  },
  {
    id: 'coin-change',
    title: 'Coin Change (Minimum Coins)',
    category: 'dp',
    difficulty: 'Medium',
    tags: ['Array', 'Dynamic Programming', 'Unbounded Knapsack'],
    problemStatement: {
      description: 'Given an integer array coins representing coin denominations and an integer amount, return the fewest number of coins needed to make up that amount.',
      exampleInput: 'coins = [1, 2, 5], amount = 11',
      exampleOutput: '3 (5 + 5 + 1)',
      constraints: '1 <= coins.length <= 12, 0 <= amount <= 10^4',
    },
    bruteForce: {
      explanation: 'Try all combinations of coins recursively using top-down search tree.',
      code: `function coinChangeBrute(coins, amount) {\n  function count(rem) {\n    if (rem === 0) return 0;\n    if (rem < 0) return Infinity;\n    let minCoins = Infinity;\n    for (let coin of coins) {\n      const res = count(rem - coin);\n      if (res !== Infinity) minCoins = Math.min(minCoins, res + 1);\n    }\n    return minCoins;\n  }\n  const ans = count(amount);\n  return ans === Infinity ? -1 : ans;\n}`,
      timeComplexity: 'O(S^N)',
      spaceComplexity: 'O(Amount)',
      pros: 'Exhaustive recursive tree search.',
      cons: 'Exponential time complexity due to redundant subproblems.',
    },
    optimalSolution: {
      explanation: 'Use 1D Dynamic Programming Tabulation: dp[i] represents minimum coins for target sum i. For each coin, dp[i] = min(dp[i], 1 + dp[i - coin]).',
      code: `function coinChangeOptimal(coins, amount) {\n  const dp = new Array(amount + 1).fill(Infinity);\n  dp[0] = 0;\n  for (let i = 1; i <= amount; i++) {\n    for (let coin of coins) {\n      if (i - coin >= 0) {\n        dp[i] = Math.min(dp[i], 1 + dp[i - coin]);\n      }\n    }\n  }\n  return dp[amount] === Infinity ? -1 : dp[amount];\n}`,
      timeComplexity: 'O(Amount × N)',
      spaceComplexity: 'O(Amount)',
      pros: 'Linear-time DP tabulation.',
      cons: 'Requires auxiliary DP table of size Amount + 1.',
    },
    interviewTips: {
      whenToThink: 'Whenever finding optimal combination count with unlimited item re-use.',
      commonMistakes: 'Initializing DP array with 0 instead of Infinity or amount + 1.',
    },
    patternRecognition: {
      patternName: '1D DP Tabulation / Unbounded Knapsack',
      whyThisPattern: 'Subproblem optimal answers for amount - coin build the global optimal solution.',
    },
    optimizationCoach: {
      bottleneck: 'Brute force re-calculates coin combinations for same sub-amounts.',
      optimizationIdea: 'Store minimum coins for every sub-amount 0..Amount in a 1D DP table.',
      visualTransition: 'O(S^N) Exponential Tree Search ➔ 1D Tabulation Table ➔ O(Amount × N) Linear DP',
    },
    visualComplexity: {
      type: 'linear-scan',
      stepsExplanation: 'Loops i from 1 to Amount. Evaluates N coins per amount slot.',
    },
    learningSteps: [
      { step: 1, text: 'Initialize dp array of size 12 with Infinity. dp[0] = 0.' },
      { step: 2, text: 'Amount i = 1: dp[1] = 1 (1x coin 1).' },
      { step: 3, text: 'Amount i = 5: dp[5] = 1 (1x coin 5).' },
      { step: 4, text: 'Amount i = 6: dp[6] = min(dp[5]+1, dp[4]+1) = 2 (5 + 1).' },
      { step: 5, text: 'Amount i = 11: dp[11] = min(dp[6]+1, dp[10]+1) = 3 (5 + 5 + 1).' },
    ],
  },
  {
    id: 'word-ladder',
    title: 'Word Ladder (Shortest Transformation Sequence)',
    category: 'graphs',
    difficulty: 'Hard',
    tags: ['Hash Table', 'String', 'Breadth-First Search'],
    problemStatement: {
      description: 'Given two words (beginWord and endWord), and a dictionary wordList, return the number of words in the shortest transformation sequence from beginWord to endWord where only one letter can change at a time.',
      exampleInput: 'beginWord = "hit", endWord = "cog", wordList = ["hot","dot","dog","lot","log","cog"]',
      exampleOutput: '5 ("hit" -> "hot" -> "dot" -> "dog" -> "cog")',
      constraints: '1 <= beginWord.length <= 10, wordList.length <= 5000',
    },
    bruteForce: {
      explanation: 'Use DFS to explore all valid single-character mutation paths, recording minimum sequence length.',
      code: `function ladderLengthDFS(beginWord, endWord, wordList) {\n  const wordSet = new Set(wordList);\n  if (!wordSet.has(endWord)) return 0;\n  let minLen = Infinity;\n  function dfs(curr, visited, depth) {\n    if (curr === endWord) { minLen = Math.min(minLen, depth); return; }\n    for (let i = 0; i < curr.length; i++) {\n      for (let ch = 97; ch <= 122; ch++) {\n        const next = curr.slice(0, i) + String.fromCharCode(ch) + curr.slice(i + 1);\n        if (wordSet.has(next) && !visited.has(next)) {\n          visited.add(next);\n          dfs(next, visited, depth + 1);\n          visited.delete(next);\n        }\n      }\n    }\n  }\n  dfs(beginWord, new Set([beginWord]), 1);\n  return minLen === Infinity ? 0 : minLen;\n}`,
      timeComplexity: 'O(26^L × N)',
      spaceComplexity: 'O(N)',
      pros: 'Finds all paths.',
      cons: 'Gets stuck in deep paths; does not guarantee shortest path first.',
    },
    optimalSolution: {
      explanation: 'Use Breadth-First Search (BFS) with a queue. BFS explores level-by-level, guaranteeing the first time endWord is reached, the path length is minimal.',
      code: `function ladderLengthOptimal(beginWord, endWord, wordList) {\n  const wordSet = new Set(wordList);\n  if (!wordSet.has(endWord)) return 0;\n  const queue = [[beginWord, 1]];\n  const visited = new Set([beginWord]);\n  while (queue.length > 0) {\n    const [word, level] = queue.shift();\n    if (word === endWord) return level;\n    for (let i = 0; i < word.length; i++) {\n      for (let c = 97; c <= 122; c++) {\n        const newChar = String.fromCharCode(c);\n        if (newChar === word[i]) continue;\n        const nextWord = word.slice(0, i) + newChar + word.slice(i + 1);\n        if (wordSet.has(nextWord) && !visited.has(nextWord)) {\n          visited.add(nextWord);\n          queue.push([nextWord, level + 1]);\n        }\n      }\n    }\n  }\n  return 0;\n}`,
      timeComplexity: 'O(L × 26 × N)',
      spaceComplexity: 'O(N)',
      pros: 'Guaranteed shortest path; stops immediately upon reaching endWord.',
      cons: 'Requires queue and visited set memory.',
    },
    interviewTips: {
      whenToThink: 'Whenever finding shortest transformation steps in unweighted state graphs.',
      commonMistakes: 'Using DFS instead of BFS for unweighted shortest path problems.',
    },
    patternRecognition: {
      patternName: 'BFS Unweighted Shortest Path / State Frontier',
      whyThisPattern: 'BFS expands expanding wavefronts level-by-level, ensuring optimal distance.',
    },
    optimizationCoach: {
      bottleneck: 'DFS explores deep suboptimal paths before finding shortest transformation.',
      optimizationIdea: 'BFS queue expands level by level, stopping instantly when target is reached.',
      visualTransition: 'DFS Deep Search ➔ BFS Level-Order Queue ➔ Shortest Transformation Path',
    },
    visualComplexity: {
      type: 'tree-traversal',
      stepsExplanation: 'Queue visits each valid word in wordList at most once.',
    },
    learningSteps: [
      { step: 1, text: 'Initialize queue with [["hit", 1]]. Mark "hit" visited.' },
      { step: 2, text: 'Level 1: Mutate "hit" -> find "hot" in wordList. Enqueue ["hot", 2].' },
      { step: 3, text: 'Level 2: Mutate "hot" -> find "dot" and "lot". Enqueue ["dot", 3], ["lot", 3].' },
      { step: 4, text: 'Level 3: Mutate "dot" -> find "dog". Enqueue ["dog", 4].' },
      { step: 5, text: 'Level 4: Mutate "dog" -> find "cog"! Target reached. Return sequence length = 5.' },
    ],
  },
]

export const getProblemById = (id) => dsaProblems.find((p) => p.id === id) || dsaProblems[0]
export const getProblemsByCategory = (categoryId) => dsaProblems.filter((p) => p.category === categoryId)
