/**
 * Comprehensive 120+ Essential DSA Topics & Interview Preparation Roadmap Engine
 * Covers 18 primary categories (221 enumerated topics), 20 Must-Master Problem Solving Patterns,
 * and 18 Priority Tiers for top tech companies (Google, Meta, Amazon, Microsoft, Uber, Atlassian, Adobe).
 */

export const dsaRoadmapCategories = [
  {
    id: 'complexity',
    num: 1,
    title: 'Time & Space Complexity',
    icon: '⏱️',
    description: 'Asymptotic analysis, mathematical bounds, recurrence relations, and complexity trade-offs.',
    totalTopics: 10,
  },
  {
    id: 'arrays',
    num: 2,
    title: 'Arrays',
    icon: '📦',
    description: 'Contiguous memory, prefix math, sliding windows, multi-pointer scans, and matrix manipulations.',
    totalTopics: 15,
  },
  {
    id: 'strings',
    num: 3,
    title: 'Strings',
    icon: '📝',
    description: 'Character frequency maps, substring search, pattern matching algorithms, and suffix arrays.',
    totalTopics: 15,
  },
  {
    id: 'linked-lists',
    num: 4,
    title: 'Linked Lists',
    icon: '🔗',
    description: 'Node pointer manipulation, fast/slow pointer cycle detection, reversing, and caching structures.',
    totalTopics: 10,
  },
  {
    id: 'stack',
    num: 5,
    title: 'Stack',
    icon: '🥞',
    description: 'LIFO execution, monotonic stacks, expression parsing, and historical boundary tracking.',
    totalTopics: 10,
  },
  {
    id: 'queue-deque',
    num: 6,
    title: 'Queue & Deque',
    icon: '🚶',
    description: 'FIFO buffers, double-ended queues, monotonic sliding window maximums, and priority queues.',
    totalTopics: 8,
  },
  {
    id: 'hashing',
    num: 7,
    title: 'Hashing',
    icon: '🔑',
    description: 'Constant time lookups, collision resolution strategies, ordered maps, and coordinate compression.',
    totalTopics: 7,
  },
  {
    id: 'binary-search',
    num: 8,
    title: 'Binary Search',
    icon: '🔍',
    description: 'Logarithmic search space halving, search-on-answer bisection, and rotated array searching.',
    totalTopics: 10,
  },
  {
    id: 'sorting',
    num: 9,
    title: 'Sorting',
    icon: '🔀',
    description: 'Comparison and non-comparison sorting algorithms, partitioning, and Quick Select k-th element.',
    totalTopics: 10,
  },
  {
    id: 'trees',
    num: 10,
    title: 'Trees',
    icon: '🌳',
    description: 'Binary trees, balanced search trees (AVL, Red-Black), Segment/Fenwick trees, and LCA lifting.',
    totalTopics: 18,
  },
  {
    id: 'heaps',
    num: 11,
    title: 'Heaps',
    icon: '⛰️',
    description: 'Priority heaps, min/max heapify operations, top-K element tracking, and streaming medians.',
    totalTopics: 5,
  },
  {
    id: 'graphs',
    num: 12,
    title: 'Graphs',
    icon: '🌐',
    description: 'Adjacency graphs, BFS/DFS, topological sorting, DSU, shortest path (Dijkstra, Bellman-Ford), and SCCs.',
    totalTopics: 25,
  },
  {
    id: 'dp',
    num: 13,
    title: 'Dynamic Programming',
    icon: '🧩',
    description: 'Overlapping subproblems, memoization vs tabulation, knapsacks, LIS/LCS, bitmask DP, and digit DP.',
    totalTopics: 20,
  },
  {
    id: 'greedy',
    num: 14,
    title: 'Greedy',
    icon: '⚡',
    description: 'Locally optimal step choices leading to globally optimal choices and interval scheduling.',
    totalTopics: 10,
  },
  {
    id: 'backtracking',
    num: 15,
    title: 'Backtracking',
    icon: '🌲',
    description: 'State space tree exploration with prune-and-undo logic for combinatorial decision search.',
    totalTopics: 8,
  },
  {
    id: 'bit-manipulation',
    num: 16,
    title: 'Bit Manipulation',
    icon: '01',
    description: 'Bitwise XOR tricks, masking, set bit counting, Gray code, and binary subset enumeration.',
    totalTopics: 12,
  },
  {
    id: 'math',
    num: 17,
    title: 'Mathematical Algorithms',
    icon: '📐',
    description: 'GCD/LCM, Sieve of Eratosthenes, modular arithmetic, fast exponentiation, and combinatorics.',
    totalTopics: 10,
  },
  {
    id: 'advanced',
    num: 18,
    title: 'Advanced Techniques',
    icon: '🚀',
    description: 'Meet in the middle, Mo\'s algorithm, line sweep, persistent segment trees, and HLD.',
    totalTopics: 18,
  },
]

export const mustMasterPatterns = [
  {
    id: 'pattern-two-pointers',
    name: 'Two Pointers',
    description: 'Converging left/right or fast/slow pointers to process sorted arrays or linked lists in O(N) time.',
    exampleProblem: 'Two Sum II, Container With Most Water, Valid Palindrome',
    priority: 'Must Master (High Frequency)',
    icon: '👉',
  },
  {
    id: 'pattern-sliding-window',
    name: 'Sliding Window',
    description: 'Maintain a dynamic subsegment window over contiguous arrays or strings to track sum, max, or distinct count.',
    exampleProblem: 'Longest Substring Without Repeating Characters, Minimum Window Substring',
    priority: 'Must Master (High Frequency)',
    icon: '🪟',
  },
  {
    id: 'pattern-fast-slow',
    name: 'Fast & Slow Pointer',
    description: 'Hare & tortoise pointer movement for cycle detection, finding middle nodes, or happy numbers.',
    exampleProblem: 'Linked List Cycle (Floyd\'s Algorithm), Find Duplicate Number',
    priority: 'Must Master (High Frequency)',
    icon: '🐢',
  },
  {
    id: 'pattern-prefix-sum',
    name: 'Prefix Sum',
    description: 'Precompute cumulative sums array to answer range sum queries in O(1) time after O(N) precomputation.',
    exampleProblem: 'Subarray Sum Equals K, Range Sum Query',
    priority: 'Must Master (High Frequency)',
    icon: '➕',
  },
  {
    id: 'pattern-difference-array',
    name: 'Difference Array',
    description: 'Efficiently update range values over multiple query operations in O(1) time per query.',
    exampleProblem: 'Corporate Flight Bookings, Range Addition',
    priority: 'Core Pattern',
    icon: '📊',
  },
  {
    id: 'pattern-bs-on-answer',
    name: 'Binary Search on Answer',
    description: 'Bisect a monotonic decision search space [low, high] when checking validity takes O(N) time.',
    exampleProblem: 'Koko Eating Bananas, Capacity To Ship Packages Within D Days',
    priority: 'Must Master (High Frequency)',
    icon: '🔍',
  },
  {
    id: 'pattern-monotonic-stack',
    name: 'Monotonic Stack',
    description: 'Maintain an increasing or decreasing stack to find next/previous greater/smaller elements in O(N) time.',
    exampleProblem: 'Daily Temperatures, Largest Rectangle in Histogram, Trapping Rain Water',
    priority: 'Must Master (High Frequency)',
    icon: '🥞',
  },
  {
    id: 'pattern-monotonic-queue',
    name: 'Monotonic Queue',
    description: 'Maintain a deque with monotonic elements to find sliding window maximum/minimum in O(N) time.',
    exampleProblem: 'Sliding Window Maximum',
    priority: 'Core Pattern',
    icon: '🚶',
  },
  {
    id: 'pattern-greedy',
    name: 'Greedy',
    description: 'Choose locally optimal choice at each step to reach a global optimum.',
    exampleProblem: 'Jump Game, Gas Station, Task Scheduler',
    priority: 'Must Master (High Frequency)',
    icon: '⚡',
  },
  {
    id: 'pattern-backtracking',
    name: 'Backtracking',
    description: 'Recursively construct decision candidates, explore deeper, and undo choices upon hitting invalid states.',
    exampleProblem: 'N-Queens, Sudoku Solver, Word Search, Subsets',
    priority: 'Must Master (High Frequency)',
    icon: '🌲',
  },
  {
    id: 'pattern-dfs',
    name: 'Depth-First Search (DFS)',
    description: 'Traverse trees or graphs as deeply as possible along each branch before backtracking.',
    exampleProblem: 'Number of Islands, Path Sum, Graph Connected Components',
    priority: 'Must Master (High Frequency)',
    icon: '🏊',
  },
  {
    id: 'pattern-bfs',
    name: 'Breadth-First Search (BFS)',
    description: 'Level-order traversal using a queue to find shortest paths in unweighted graphs or grids.',
    exampleProblem: 'Shortest Path in Binary Matrix, Word Ladder, Rotting Oranges',
    priority: 'Must Master (High Frequency)',
    icon: '🌊',
  },
  {
    id: 'pattern-topological-sort',
    name: 'Topological Sort (Kahn\'s Algorithm)',
    description: 'Linear ordering of vertices in a Directed Acyclic Graph (DAG) based on in-degree dependencies.',
    exampleProblem: 'Course Schedule I & II, Alien Dictionary',
    priority: 'Must Master (High Frequency)',
    icon: '🎓',
  },
  {
    id: 'pattern-union-find',
    name: 'Union Find (DSU)',
    description: 'Disjoint set data structure with path compression & rank to track connected components and cycle detection.',
    exampleProblem: 'Redundant Connection, Number of Provinces, Kruskal\'s MST',
    priority: 'Must Master (High Frequency)',
    icon: '🔗',
  },
  {
    id: 'pattern-dijkstra',
    name: 'Dijkstra\'s Algorithm',
    description: 'Priority Queue based greedy shortest path algorithm for non-negative weighted graphs.',
    exampleProblem: 'Network Delay Time, Path with Minimum Effort',
    priority: 'Must Master (High Frequency)',
    icon: '🧭',
  },
  {
    id: 'pattern-dp',
    name: 'Dynamic Programming',
    description: 'Break complex optimization problems into overlapping subproblems with optimal substructure.',
    exampleProblem: 'Climbing Stairs, 0/1 Knapsack, Longest Common Subsequence, Coin Change',
    priority: 'Must Master (High Frequency)',
    icon: '🧩',
  },
  {
    id: 'pattern-bitmasking',
    name: 'Bitmasking',
    description: 'Represent sets and states as binary bit vectors for O(1) state transitions and subset operations.',
    exampleProblem: 'Single Number, Partition to K Equal Sum Subsets, Travelling Salesperson DP',
    priority: 'Core Pattern',
    icon: '01',
  },
  {
    id: 'pattern-divide-and-conquer',
    name: 'Divide and Conquer',
    description: 'Break problem into independent subproblems, solve recursively, and combine results.',
    exampleProblem: 'Merge Sort, Quick Select, Majority Element',
    priority: 'Core Pattern',
    icon: '✂️',
  },
  {
    id: 'pattern-meet-in-middle',
    name: 'Meet in the Middle',
    description: 'Reduce exponential search space O(2^N) down to O(2^(N/2)) by splitting search into two halves.',
    exampleProblem: '4Sum, Partition Array Into Two Arrays to Minimize Sum Difference',
    priority: 'Advanced Interview Pattern',
    icon: '🤝',
  },
  {
    id: 'pattern-kadanes',
    name: 'Kadane\'s Algorithm',
    description: 'Dynamic programming scan to find maximum contiguous subarray sum in O(N) time and O(1) space.',
    exampleProblem: 'Maximum Subarray, Maximum Product Subarray',
    priority: 'Must Master (High Frequency)',
    icon: '📈',
  },
]

export const priorityOrder = [
  { tier: 1, name: 'Arrays & Strings', categories: ['arrays', 'strings'] },
  { tier: 2, name: 'Hashing', categories: ['hashing'] },
  { tier: 3, name: 'Two Pointers', categories: ['arrays'] },
  { tier: 4, name: 'Sliding Window', categories: ['arrays', 'strings'] },
  { tier: 5, name: 'Binary Search', categories: ['binary-search'] },
  { tier: 6, name: 'Linked Lists', categories: ['linked-lists'] },
  { tier: 7, name: 'Stack & Queue', categories: ['stack', 'queue-deque'] },
  { tier: 8, name: 'Trees & BST', categories: ['trees'] },
  { tier: 9, name: 'Heaps', categories: ['heaps'] },
  { tier: 10, name: 'Graphs (BFS/DFS)', categories: ['graphs'] },
  { tier: 11, name: 'Recursion & Backtracking', categories: ['backtracking'] },
  { tier: 12, name: 'Dynamic Programming', categories: ['dp'] },
  { tier: 13, name: 'Greedy Algorithms', categories: ['greedy'] },
  { tier: 14, name: 'Bit Manipulation', categories: ['bit-manipulation'] },
  { tier: 15, name: 'Advanced Trees (Segment Tree, Fenwick)', categories: ['trees'] },
  { tier: 16, name: 'Advanced Graph Algorithms', categories: ['graphs'] },
  { tier: 17, name: 'String Algorithms (KMP, Trie, Rabin–Karp)', categories: ['strings'] },
  { tier: 18, name: 'Advanced Techniques (Mo\'s Algorithm, HLD)', categories: ['advanced'] },
]

export const dsaTopics = [
  // 1. Time & Space Complexity (1..10)
  { num: 1, title: 'Big O Notation', categoryId: 'complexity', categoryName: 'Time & Space Complexity', priorityTier: 1, pattern: 'Complexity Analysis', description: 'Upper bound asymptotic notation describing worst-case growth rate of an algorithm.', linkedProblemId: null },
  { num: 2, title: 'Big Omega', categoryId: 'complexity', categoryName: 'Time & Space Complexity', priorityTier: 1, pattern: 'Complexity Analysis', description: 'Lower bound asymptotic notation describing best-case growth rate limits.', linkedProblemId: null },
  { num: 3, title: 'Big Theta', categoryId: 'complexity', categoryName: 'Time & Space Complexity', priorityTier: 1, pattern: 'Complexity Analysis', description: 'Tight bound notation describing exact asymptotic growth when upper and lower bounds coincide.', linkedProblemId: null },
  { num: 4, title: 'Time Complexity Analysis', categoryId: 'complexity', categoryName: 'Time & Space Complexity', priorityTier: 1, pattern: 'Complexity Analysis', description: 'Counting dominant operations as a function of input size N.', linkedProblemId: null },
  { num: 5, title: 'Space Complexity', categoryId: 'complexity', categoryName: 'Time & Space Complexity', priorityTier: 1, pattern: 'Complexity Analysis', description: 'Measuring auxiliary memory allocations, call stack frames, and dynamic heap usage.', linkedProblemId: null },
  { num: 6, title: 'Amortized Analysis', categoryId: 'complexity', categoryName: 'Time & Space Complexity', priorityTier: 1, pattern: 'Complexity Analysis', description: 'Averaging operation time over a sequence of operations (e.g. Dynamic Array resizing).', linkedProblemId: null },
  { num: 7, title: 'Recursion Tree Analysis', categoryId: 'complexity', categoryName: 'Time & Space Complexity', priorityTier: 1, pattern: 'Recursion', description: 'Visualizing recursive call branches and summing node work across tree levels.', linkedProblemId: null },
  { num: 8, title: 'Master Theorem', categoryId: 'complexity', categoryName: 'Time & Space Complexity', priorityTier: 1, pattern: 'Divide and Conquer', description: 'Asymptotic bounds solution for divide-and-conquer recurrences T(n) = aT(n/b) + f(n).', linkedProblemId: null },
  { num: 9, title: 'Asymptotic Comparison', categoryId: 'complexity', categoryName: 'Time & Space Complexity', priorityTier: 1, pattern: 'Complexity Analysis', description: 'Comparing ordering of functions: O(1) < O(log N) < O(N) < O(N log N) < O(N^2) < O(2^N) < O(N!).', linkedProblemId: null },
  { num: 10, title: 'Complexity Trade-offs', categoryId: 'complexity', categoryName: 'Time & Space Complexity', priorityTier: 1, pattern: 'Complexity Analysis', description: 'Trading O(N) space for O(1) lookup speed (HashMaps) or trading time for low memory.', linkedProblemId: null },

  // 2. Arrays (11..25)
  { num: 11, title: 'Array Traversal', categoryId: 'arrays', categoryName: 'Arrays', priorityTier: 1, pattern: 'Two Pointers', description: 'Iterating contiguous memory blocks with linear cache efficiency.', linkedProblemId: 'two-sum' },
  { num: 12, title: 'Prefix Sum', categoryId: 'arrays', categoryName: 'Arrays', priorityTier: 1, pattern: 'Prefix Sum', description: 'Precomputing cumulative sums for O(1) range sum queries.', linkedProblemId: null },
  { num: 13, title: 'Difference Array', categoryId: 'arrays', categoryName: 'Arrays', priorityTier: 1, pattern: 'Difference Array', description: 'Range update operations in O(1) time using delta arrays.', linkedProblemId: null },
  { num: 14, title: 'Sliding Window', categoryId: 'arrays', categoryName: 'Arrays', priorityTier: 4, pattern: 'Sliding Window', description: 'Maintaining a contiguous window range over arrays to track max, min, or sum.', linkedProblemId: 'longest-substring-without-repeating-characters' },
  { num: 15, title: 'Two Pointers', categoryId: 'arrays', categoryName: 'Arrays', priorityTier: 3, pattern: 'Two Pointers', description: 'Scanning arrays using inward or outward pointer pairs.', linkedProblemId: 'container-with-most-water' },
  { num: 16, title: 'Kadane\'s Algorithm', categoryId: 'arrays', categoryName: 'Arrays', priorityTier: 1, pattern: 'Kadane\'s Algorithm', description: 'Single-pass scan for maximum subarray sum by discarding negative prefixes.', linkedProblemId: 'maximum-subarray' },
  { num: 17, title: 'Dutch National Flag Algorithm', categoryId: 'arrays', categoryName: 'Arrays', priorityTier: 1, pattern: 'Two Pointers', description: '3-way in-place partitioning of 0s, 1s, and 2s in linear time.', linkedProblemId: null },
  { num: 18, title: 'Rotate Array', categoryId: 'arrays', categoryName: 'Arrays', priorityTier: 1, pattern: 'Two Pointers', description: 'In-place array rotation by K steps using 3-step array reversal.', linkedProblemId: null },
  { num: 19, title: 'Merge Intervals', categoryId: 'arrays', categoryName: 'Arrays', priorityTier: 1, pattern: 'Greedy', description: 'Sorting range intervals by start time and merging overlapping boundaries.', linkedProblemId: 'merge-intervals' },
  { num: 20, title: 'Interval Scheduling', categoryId: 'arrays', categoryName: 'Arrays', priorityTier: 13, pattern: 'Greedy', description: 'Selecting non-overlapping intervals greedily sorted by end time.', linkedProblemId: null },
  { num: 21, title: 'Majority Element (Moore\'s Voting)', categoryId: 'arrays', categoryName: 'Arrays', priorityTier: 1, pattern: 'Greedy', description: 'O(N) time and O(1) space vote counter for elements occurring > N/2 times.', linkedProblemId: null },
  { num: 22, title: 'Rearrangement Problems', categoryId: 'arrays', categoryName: 'Arrays', priorityTier: 1, pattern: 'Two Pointers', description: 'Re-ordering positive/negative numbers or alternating parity.', linkedProblemId: null },
  { num: 23, title: 'Matrix Traversal', categoryId: 'arrays', categoryName: 'Arrays', priorityTier: 1, pattern: 'DFS/BFS', description: 'Row-major and column-major iteration over 2D grid arrays.', linkedProblemId: null },
  { num: 24, title: 'Spiral Matrix', categoryId: 'arrays', categoryName: 'Arrays', priorityTier: 1, pattern: 'Two Pointers', description: 'Boundary shrinkage (top, bottom, left, right) to output matrix spiral order.', linkedProblemId: null },
  { num: 25, title: 'Matrix Rotation', categoryId: 'arrays', categoryName: 'Arrays', priorityTier: 1, pattern: 'Two Pointers', description: 'In-place 90-degree matrix rotation via matrix transpose followed by row reversal.', linkedProblemId: null },

  // 3. Strings (26..40)
  { num: 26, title: 'String Traversal', categoryId: 'strings', categoryName: 'Strings', priorityTier: 1, pattern: 'Two Pointers', description: 'Processing character sequences and ASCII/UTF-8 code points.', linkedProblemId: null },
  { num: 27, title: 'Character Frequency', categoryId: 'strings', categoryName: 'Strings', priorityTier: 2, pattern: 'Hashing', description: 'Counting character occurrences using 26-slot frequency arrays or HashMaps.', linkedProblemId: 'valid-anagram' },
  { num: 28, title: 'Palindrome Checking', categoryId: 'strings', categoryName: 'Strings', priorityTier: 1, pattern: 'Two Pointers', description: 'Comparing front and back characters moving inward towards middle.', linkedProblemId: 'valid-palindrome' },
  { num: 29, title: 'Anagrams', categoryId: 'strings', categoryName: 'Strings', priorityTier: 2, pattern: 'Hashing', description: 'Group or verify string permutations using character frequency hashes.', linkedProblemId: 'group-anagrams' },
  { num: 30, title: 'Longest Common Prefix', categoryId: 'strings', categoryName: 'Strings', priorityTier: 1, pattern: 'Two Pointers', description: 'Horizontal and vertical scanning across array of string prefixes.', linkedProblemId: null },
  { num: 31, title: 'Pattern Matching', categoryId: 'strings', categoryName: 'Strings', priorityTier: 17, pattern: 'Sliding Window', description: 'Checking string pattern occurrences in text body.', linkedProblemId: null },
  { num: 32, title: 'Rabin-Karp', categoryId: 'strings', categoryName: 'Strings', priorityTier: 17, pattern: 'Rolling Hash', description: 'Pattern search using polynomial rolling hashes in O(N+M) average time.', linkedProblemId: null },
  { num: 33, title: 'KMP Algorithm', categoryId: 'strings', categoryName: 'Strings', priorityTier: 17, pattern: 'Prefix Function (LPS)', description: 'Knuth-Morris-Pratt string matching avoiding re-scans using Longest Proper Prefix array.', linkedProblemId: 'kmp-string-matching' },
  { num: 34, title: 'Z Algorithm', categoryId: 'strings', categoryName: 'Strings', priorityTier: 17, pattern: 'Z-Array', description: 'Linear time string matching via Z-array storing longest match starting at i.', linkedProblemId: null },
  { num: 35, title: 'Manacher\'s Algorithm', categoryId: 'strings', categoryName: 'Strings', priorityTier: 17, pattern: 'Palindrome Radius', description: 'O(N) linear time search for longest palindromic substring using symmetry.', linkedProblemId: null },
  { num: 36, title: 'Rolling Hash', categoryId: 'strings', categoryName: 'Strings', priorityTier: 17, pattern: 'Rolling Hash', description: 'Constant-time hash update when sliding a fixed-width window across a string.', linkedProblemId: null },
  { num: 37, title: 'Trie on Strings', categoryId: 'strings', categoryName: 'Strings', priorityTier: 17, pattern: 'Trie', description: 'Prefix tree data structure for fast string dictionary insertion and lookup.', linkedProblemId: null },
  { num: 38, title: 'String Compression', categoryId: 'strings', categoryName: 'Strings', priorityTier: 1, pattern: 'Two Pointers', description: 'In-place run-length encoding of consecutive duplicate characters.', linkedProblemId: null },
  { num: 39, title: 'Substring Search', categoryId: 'strings', categoryName: 'Strings', priorityTier: 1, pattern: 'Sliding Window', description: 'Searching for substring occurrences with exact or wildcard criteria.', linkedProblemId: null },
  { num: 40, title: 'Suffix Array (Basics)', categoryId: 'strings', categoryName: 'Strings', priorityTier: 17, pattern: 'Suffix Sorting', description: 'Sorted array of all string suffixes for advanced substring queries.', linkedProblemId: null },

  // 4. Linked Lists (41..50)
  { num: 41, title: 'Singly Linked List', categoryId: 'linked-lists', categoryName: 'Linked Lists', priorityTier: 6, pattern: 'Node Pointer', description: 'Linear sequence of nodes linked via single next references.', linkedProblemId: null },
  { num: 42, title: 'Doubly Linked List', categoryId: 'linked-lists', categoryName: 'Linked Lists', priorityTier: 6, pattern: 'Node Pointer', description: 'Bidirectional nodes linked via prev and next references for O(1) removal.', linkedProblemId: null },
  { num: 43, title: 'Circular Linked List', categoryId: 'linked-lists', categoryName: 'Linked Lists', priorityTier: 6, pattern: 'Node Pointer', description: 'Linked list where tail node points back to the head node.', linkedProblemId: null },
  { num: 44, title: 'Reverse Linked List', categoryId: 'linked-lists', categoryName: 'Linked Lists', priorityTier: 6, pattern: 'Two Pointers', description: 'In-place pointer reversal using prev, curr, and next node references.', linkedProblemId: 'reverse-linked-list' },
  { num: 45, title: 'Fast & Slow Pointer', categoryId: 'linked-lists', categoryName: 'Linked Lists', priorityTier: 6, pattern: 'Fast & Slow Pointer', description: 'Two pointers moving at 1x and 2x speeds to find middle node or cycle.', linkedProblemId: null },
  { num: 46, title: 'Detect Cycle (Floyd)', categoryId: 'linked-lists', categoryName: 'Linked Lists', priorityTier: 6, pattern: 'Fast & Slow Pointer', description: 'Floyd\'s cycle-finding algorithm to detect loop and locate cycle entry node.', linkedProblemId: 'linked-list-cycle' },
  { num: 47, title: 'Merge Lists', categoryId: 'linked-lists', categoryName: 'Linked Lists', priorityTier: 6, pattern: 'Two Pointers', description: 'Merging two sorted linked lists into a single sorted list.', linkedProblemId: null },
  { num: 48, title: 'Intersection of Lists', categoryId: 'linked-lists', categoryName: 'Linked Lists', priorityTier: 6, pattern: 'Two Pointers', description: 'Finding node where two lists merge by switching pointer paths at tails.', linkedProblemId: null },
  { num: 49, title: 'LRU Cache', categoryId: 'linked-lists', categoryName: 'Linked Lists', priorityTier: 6, pattern: 'Doubly Linked List + HashMap', description: 'Least Recently Used cache with O(1) get and put using HashMap + Doubly Linked List.', linkedProblemId: 'lru-cache' },
  { num: 50, title: 'Copy Random Pointer', categoryId: 'linked-lists', categoryName: 'Linked Lists', priorityTier: 6, pattern: 'Node Interleaving', description: 'Deep cloning a linked list with random pointers using interweaving or HashMap.', linkedProblemId: null },

  // 5. Stack (51..60)
  { num: 51, title: 'Stack Basics', categoryId: 'stack', categoryName: 'Stack', priorityTier: 7, pattern: 'Stack (LIFO)', description: 'Last-In-First-Out data structure supporting push, pop, and top operations in O(1).', linkedProblemId: null },
  { num: 52, title: 'Monotonic Stack', categoryId: 'stack', categoryName: 'Stack', priorityTier: 7, pattern: 'Monotonic Stack', description: 'Stack maintaining strictly increasing or decreasing elements for nearest greater/smaller queries.', linkedProblemId: 'daily-temperatures' },
  { num: 53, title: 'Next Greater Element', categoryId: 'stack', categoryName: 'Stack', priorityTier: 7, pattern: 'Monotonic Stack', description: 'Finding the first element to the right larger than current element in O(N).', linkedProblemId: null },
  { num: 54, title: 'Previous Greater Element', categoryId: 'stack', categoryName: 'Stack', priorityTier: 7, pattern: 'Monotonic Stack', description: 'Finding nearest larger element to the left using monotonic stack scan.', linkedProblemId: null },
  { num: 55, title: 'Largest Rectangle Histogram', categoryId: 'stack', categoryName: 'Stack', priorityTier: 7, pattern: 'Monotonic Stack', description: 'Finding maximum rectangular area in histogram using stack for left/right bounds.', linkedProblemId: 'trapping-rain-water' },
  { num: 56, title: 'Valid Parentheses', categoryId: 'stack', categoryName: 'Stack', priorityTier: 7, pattern: 'Stack (LIFO)', description: 'Verifying balanced brackets (), {}, [] using LIFO stack push and pop.', linkedProblemId: 'valid-parentheses' },
  { num: 57, title: 'Min Stack', categoryId: 'stack', categoryName: 'Stack', priorityTier: 7, pattern: 'Stack (LIFO)', description: 'Designing a stack that retrieves minimum element in O(1) time using auxiliary minimums.', linkedProblemId: 'min-stack' },
  { num: 58, title: 'Expression Evaluation', categoryId: 'stack', categoryName: 'Stack', priorityTier: 7, pattern: 'Stack (LIFO)', description: 'Evaluating mathematical expressions containing operators and parentheses.', linkedProblemId: null },
  { num: 59, title: 'Infix/Postfix/Prefix', categoryId: 'stack', categoryName: 'Stack', priorityTier: 7, pattern: 'Stack (LIFO)', description: 'Converting between infix, postfix (RPN), and prefix notation using Shunting-Yard.', linkedProblemId: null },
  { num: 60, title: 'Stock Span', categoryId: 'stack', categoryName: 'Stack', priorityTier: 7, pattern: 'Monotonic Stack', description: 'Counting consecutive smaller stock prices prior to current day using monotonic stack.', linkedProblemId: null },

  // 6. Queue & Deque (61..68)
  { num: 61, title: 'Queue', categoryId: 'queue-deque', categoryName: 'Queue & Deque', priorityTier: 7, pattern: 'Queue (FIFO)', description: 'First-In-First-Out data structure supporting enqueue and dequeue operations.', linkedProblemId: null },
  { num: 62, title: 'Circular Queue', categoryId: 'queue-deque', categoryName: 'Queue & Deque', priorityTier: 7, pattern: 'Circular Buffer', description: 'Fixed-size ring buffer utilizing modulo arithmetic for wrap-around enqueue.', linkedProblemId: null },
  { num: 63, title: 'Deque', categoryId: 'queue-deque', categoryName: 'Queue & Deque', priorityTier: 7, pattern: 'Double-Ended Queue', description: 'Double-ended queue allowing insertion and deletion at both front and back in O(1).', linkedProblemId: null },
  { num: 64, title: 'Monotonic Queue', categoryId: 'queue-deque', categoryName: 'Queue & Deque', priorityTier: 7, pattern: 'Monotonic Queue', description: 'Deque keeping elements in monotonic order for maximums in dynamic windows.', linkedProblemId: null },
  { num: 65, title: 'Priority Queue', categoryId: 'queue-deque', categoryName: 'Queue & Deque', priorityTier: 9, pattern: 'Heap', description: 'Queue ordering elements by priority weight using underlying Min/Max Heap.', linkedProblemId: null },
  { num: 66, title: 'Heap Queue', categoryId: 'queue-deque', categoryName: 'Queue & Deque', priorityTier: 9, pattern: 'Heap', description: 'Binary heap implementation backing priority queue operations in O(log N).', linkedProblemId: null },
  { num: 67, title: 'BFS Queue', categoryId: 'queue-deque', categoryName: 'Queue & Deque', priorityTier: 10, pattern: 'BFS', description: 'Frontier queue maintaining graph nodes level-by-level for shortest path search.', linkedProblemId: null },
  { num: 68, title: 'Sliding Window Maximum', categoryId: 'queue-deque', categoryName: 'Queue & Deque', priorityTier: 7, pattern: 'Monotonic Queue', description: 'Finding max element in every sliding window of size K in O(N) using Monotonic Deque.', linkedProblemId: 'sliding-window-maximum' },

  // 7. Hashing (69..75)
  { num: 69, title: 'HashMap', categoryId: 'hashing', categoryName: 'Hashing', priorityTier: 2, pattern: 'Hashing', description: 'Key-value map providing average O(1) insertion, deletion, and lookup.', linkedProblemId: 'two-sum' },
  { num: 70, title: 'HashSet', categoryId: 'hashing', categoryName: 'Hashing', priorityTier: 2, pattern: 'Hashing', description: 'Set collection storing unique elements with O(1) membership testing.', linkedProblemId: null },
  { num: 71, title: 'Frequency Counting', categoryId: 'hashing', categoryName: 'Hashing', priorityTier: 2, pattern: 'Hashing', description: 'Counting item frequencies in O(N) time for anagrams or majority elements.', linkedProblemId: 'valid-anagram' },
  { num: 72, title: 'Collision Handling', categoryId: 'hashing', categoryName: 'Hashing', priorityTier: 2, pattern: 'Hashing', description: 'Separate chaining (linked list buckets) vs open addressing (linear/quadratic probing).', linkedProblemId: null },
  { num: 73, title: 'Custom Hashing', categoryId: 'hashing', categoryName: 'Hashing', priorityTier: 2, pattern: 'Hashing', description: 'Writing custom hash functions for objects, tuples, or complex data structures.', linkedProblemId: null },
  { num: 74, title: 'Ordered Map', categoryId: 'hashing', categoryName: 'Hashing', priorityTier: 2, pattern: 'BST / Red-Black Tree', description: 'Balanced BST backed map preserving sorted key order with O(log N) operations.', linkedProblemId: null },
  { num: 75, title: 'Coordinate Compression', categoryId: 'hashing', categoryName: 'Hashing', priorityTier: 2, pattern: 'Hashing', description: 'Mapping large sparse ranges to compact zero-indexed ranks for Segment Trees or BIT.', linkedProblemId: null },

  // 8. Binary Search (76..85)
  { num: 76, title: 'Binary Search Basics', categoryId: 'binary-search', categoryName: 'Binary Search', priorityTier: 5, pattern: 'Binary Search', description: 'Divide-and-conquer halving of sorted search space [low, high] in O(log N).', linkedProblemId: 'binary-search' },
  { num: 77, title: 'Lower Bound', categoryId: 'binary-search', categoryName: 'Binary Search', priorityTier: 5, pattern: 'Binary Search', description: 'Finding first index where element is >= target value.', linkedProblemId: null },
  { num: 78, title: 'Upper Bound', categoryId: 'binary-search', categoryName: 'Binary Search', priorityTier: 5, pattern: 'Binary Search', description: 'Finding first index where element is > target value.', linkedProblemId: null },
  { num: 79, title: 'Binary Search on Answer', categoryId: 'binary-search', categoryName: 'Binary Search', priorityTier: 5, pattern: 'Binary Search on Answer', description: 'Bisection over search space [minPossible, maxPossible] when checking feasibility is O(N).', linkedProblemId: null },
  { num: 80, title: 'Peak Element', categoryId: 'binary-search', categoryName: 'Binary Search', priorityTier: 5, pattern: 'Binary Search', description: 'Finding local peak element greater than its neighbors in O(log N) time.', linkedProblemId: null },
  { num: 81, title: 'Rotated Sorted Array', categoryId: 'binary-search', categoryName: 'Binary Search', priorityTier: 5, pattern: 'Binary Search', description: 'Binary searching array rotated at unknown pivot by checking which half is sorted.', linkedProblemId: 'search-in-rotated-sorted-array' },
  { num: 82, title: 'Search in Matrix', categoryId: 'binary-search', categoryName: 'Binary Search', priorityTier: 5, pattern: 'Binary Search', description: 'Searching 2D matrix with sorted rows/columns in O(log(M*N)) or O(M+N).', linkedProblemId: null },
  { num: 83, title: 'Binary Search on Floating Point', categoryId: 'binary-search', categoryName: 'Binary Search', priorityTier: 5, pattern: 'Binary Search', description: 'Bisection with epsilon precision threshold for continuous function roots.', linkedProblemId: null },
  { num: 84, title: 'Ternary Search', categoryId: 'binary-search', categoryName: 'Binary Search', priorityTier: 5, pattern: 'Ternary Search', description: 'Dividing search space into 3 parts to find minimum or maximum of unimodal functions.', linkedProblemId: null },
  { num: 85, title: 'Exponential Search', categoryId: 'binary-search', categoryName: 'Binary Search', priorityTier: 5, pattern: 'Binary Search', description: 'Finding range containing target by powers of 2, then executing binary search.', linkedProblemId: null },

  // 9. Sorting (86..95)
  { num: 86, title: 'Bubble Sort', categoryId: 'sorting', categoryName: 'Sorting', priorityTier: 9, pattern: 'Sorting', description: 'Iterative swapping of adjacent out-of-order elements in O(N^2) time.', linkedProblemId: null },
  { num: 87, title: 'Selection Sort', categoryId: 'sorting', categoryName: 'Sorting', priorityTier: 9, pattern: 'Sorting', description: 'Repeatedly selecting minimum unsorted element and swapping to front in O(N^2).', linkedProblemId: null },
  { num: 88, title: 'Insertion Sort', categoryId: 'sorting', categoryName: 'Sorting', priorityTier: 9, pattern: 'Sorting', description: 'Building sorted array by inserting one element at a time into correct position.', linkedProblemId: null },
  { num: 89, title: 'Merge Sort', categoryId: 'sorting', categoryName: 'Sorting', priorityTier: 9, pattern: 'Divide and Conquer', description: 'Stable divide-and-conquer sort guaranteeing O(N log N) time via two-way merges.', linkedProblemId: 'merge-sort' },
  { num: 90, title: 'Quick Sort', categoryId: 'sorting', categoryName: 'Sorting', priorityTier: 9, pattern: 'Divide and Conquer', description: 'Lomuto/Hoare partitioning sort with O(N log N) average time and in-place memory.', linkedProblemId: 'quick-sort' },
  { num: 91, title: 'Heap Sort', categoryId: 'sorting', categoryName: 'Sorting', priorityTier: 9, pattern: 'Heap', description: 'In-place sort using max-heapify operations with guaranteed O(N log N) worst-case time.', linkedProblemId: null },
  { num: 92, title: 'Counting Sort', categoryId: 'sorting', categoryName: 'Sorting', priorityTier: 9, pattern: 'Non-comparison Sort', description: 'Non-comparison integer sort running in O(N + K) time using frequency counts.', linkedProblemId: null },
  { num: 93, title: 'Radix Sort', categoryId: 'sorting', categoryName: 'Sorting', priorityTier: 9, pattern: 'Non-comparison Sort', description: 'Digit-by-digit stable counting sort from least significant to most significant digit.', linkedProblemId: null },
  { num: 94, title: 'Bucket Sort', categoryId: 'sorting', categoryName: 'Sorting', priorityTier: 9, pattern: 'Non-comparison Sort', description: 'Distributing elements into buckets, sorting buckets individually, and concatenating.', linkedProblemId: null },
  { num: 95, title: 'Quick Select', categoryId: 'sorting', categoryName: 'Sorting', priorityTier: 9, pattern: 'Divide and Conquer', description: 'Quick-sort partitioning algorithm finding K-th smallest/largest element in O(N) average time.', linkedProblemId: null },

  // 10. Trees (96..113)
  { num: 96, title: 'Binary Tree Traversals', categoryId: 'trees', categoryName: 'Trees', priorityTier: 8, pattern: 'DFS/BFS', description: 'In-order, Pre-order, Post-order (DFS) and Level-order (BFS) node visits.', linkedProblemId: 'binary-tree-level-order-traversal' },
  { num: 97, title: 'BST', categoryId: 'trees', categoryName: 'Trees', priorityTier: 8, pattern: 'BST Invariant', description: 'Binary Search Tree where left child < root < right child for logarithmic lookups.', linkedProblemId: null },
  { num: 98, title: 'AVL Tree', categoryId: 'trees', categoryName: 'Trees', priorityTier: 15, pattern: 'Self-Balancing Tree', description: 'Self-balancing BST using single and double rotations maintaining height difference <= 1.', linkedProblemId: null },
  { num: 99, title: 'Red-Black Tree', categoryId: 'trees', categoryName: 'Trees', priorityTier: 15, pattern: 'Self-Balancing Tree', description: 'Self-balancing BST using node coloring (red/black) guaranteeing O(log N) tree height.', linkedProblemId: null },
  { num: 100, title: 'Tree Height', categoryId: 'trees', categoryName: 'Trees', priorityTier: 8, pattern: 'DFS', description: 'Recursive depth calculation: 1 + max(height(left), height(right)).', linkedProblemId: null },
  { num: 101, title: 'Lowest Common Ancestor', categoryId: 'trees', categoryName: 'Trees', priorityTier: 8, pattern: 'DFS', description: 'Finding deepest shared ancestor node p and q in binary tree or BST.', linkedProblemId: 'lowest-common-ancestor-of-a-binary-tree' },
  { num: 102, title: 'Diameter of Tree', categoryId: 'trees', categoryName: 'Trees', priorityTier: 8, pattern: 'DFS', description: 'Longest path between any two nodes in a tree.', linkedProblemId: null },
  { num: 103, title: 'Balanced Tree', categoryId: 'trees', categoryName: 'Trees', priorityTier: 8, pattern: 'DFS', description: 'Verifying height difference of left and right subtrees <= 1 for all nodes.', linkedProblemId: null },
  { num: 104, title: 'Serialize & Deserialize', categoryId: 'trees', categoryName: 'Trees', priorityTier: 8, pattern: 'BFS/DFS', description: 'Converting binary tree to string representation and reconstructing original structure.', linkedProblemId: null },
  { num: 105, title: 'Morris Traversal', categoryId: 'trees', categoryName: 'Trees', priorityTier: 8, pattern: 'Threaded Tree', description: 'O(N) time and O(1) auxiliary space tree traversal using threaded predecessor links.', linkedProblemId: null },
  { num: 106, title: 'Tree DP', categoryId: 'trees', categoryName: 'Trees', priorityTier: 12, pattern: 'Tree DP', description: 'Dynamic programming on trees calculating subtree states recursively.', linkedProblemId: null },
  { num: 107, title: 'Segment Tree', categoryId: 'trees', categoryName: 'Trees', priorityTier: 15, pattern: 'Segment Tree', description: 'Binary tree supporting O(log N) point/range queries and range updates over arrays.', linkedProblemId: 'segment-tree-rmq' },
  { num: 108, title: 'Fenwick Tree (BIT)', categoryId: 'trees', categoryName: 'Trees', priorityTier: 15, pattern: 'Binary Indexed Tree', description: 'Compact array tree supporting O(log N) prefix sums and point updates using bit math.', linkedProblemId: null },
  { num: 109, title: 'Sparse Table', categoryId: 'trees', categoryName: 'Trees', priorityTier: 15, pattern: 'Range Query DP', description: 'Static array range minimum query (RMQ) data structure supporting O(1) queries after O(N log N) prep.', linkedProblemId: null },
  { num: 110, title: 'Euler Tour', categoryId: 'trees', categoryName: 'Trees', priorityTier: 15, pattern: 'Tree Flattening', description: 'Flattening tree nodes into 1D array interval range via DFS entry and exit timestamps.', linkedProblemId: null },
  { num: 111, title: 'Binary Lifting', categoryId: 'trees', categoryName: 'Trees', priorityTier: 15, pattern: 'Binary Lifting', description: 'Precomputing 2^K ancestors for O(log N) Lowest Common Ancestor (LCA) queries in generic trees.', linkedProblemId: null },
  { num: 112, title: 'Heavy-Light Decomposition', categoryId: 'trees', categoryName: 'Trees', priorityTier: 15, pattern: 'HLD', description: 'Decomposing tree into heavy and light paths to answer path queries via Segment Trees in O(log^2 N).', linkedProblemId: null },
  { num: 113, title: 'Trie', categoryId: 'trees', categoryName: 'Trees', priorityTier: 17, pattern: 'Trie', description: 'Prefix tree supporting insert, search, and prefix matching in O(L) string length time.', linkedProblemId: null },

  // 11. Heaps (114..118)
  { num: 114, title: 'Min Heap', categoryId: 'heaps', categoryName: 'Heaps', priorityTier: 9, pattern: 'Heap', description: 'Complete binary tree where parent node <= children nodes.', linkedProblemId: null },
  { num: 115, title: 'Max Heap', categoryId: 'heaps', categoryName: 'Heaps', priorityTier: 9, pattern: 'Heap', description: 'Complete binary tree where parent node >= children nodes.', linkedProblemId: null },
  { num: 116, title: 'Heapify', categoryId: 'heaps', categoryName: 'Heaps', priorityTier: 9, pattern: 'Heap', description: 'O(N) bottom-up array heap construction algorithm.', linkedProblemId: null },
  { num: 117, title: 'Kth Largest/Smallest', categoryId: 'heaps', categoryName: 'Heaps', priorityTier: 9, pattern: 'Heap', description: 'Maintaining a Min/Max heap of size K to process top elements in stream in O(N log K).', linkedProblemId: 'kth-largest-element' },
  { num: 118, title: 'Merge K Sorted Lists', categoryId: 'heaps', categoryName: 'Heaps', priorityTier: 9, pattern: 'Heap', description: 'Merging K sorted arrays or linked lists in O(N log K) using min-heap priority queue.', linkedProblemId: null },

  // 12. Graphs (119..143)
  { num: 119, title: 'Graph Representation', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 10, pattern: 'Adjacency List/Matrix', description: 'Representing graph nodes and edges via Adjacency Lists or Adjacency Matrices.', linkedProblemId: null },
  { num: 120, title: 'DFS', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 10, pattern: 'DFS', description: 'Depth-first search traversal exploring along path branch before backtracking.', linkedProblemId: 'number-of-islands' },
  { num: 121, title: 'BFS', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 10, pattern: 'BFS', description: 'Breadth-first search traversal expanding wave-front level by level via Queue.', linkedProblemId: 'word-ladder' },
  { num: 122, title: 'Connected Components', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 10, pattern: 'DFS/BFS/DSU', description: 'Finding isolated subgraphs using DFS, BFS, or Disjoint Set Union.', linkedProblemId: null },
  { num: 123, title: 'Cycle Detection', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 10, pattern: 'DFS/DSU', description: 'Detecting cycles in directed graphs (three-color DFS) and undirected graphs (DSU/DFS).', linkedProblemId: null },
  { num: 124, title: 'Topological Sort', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 10, pattern: 'Topological Sort', description: 'Ordering vertices in DAG such that directed edge (u, v) places u before v.', linkedProblemId: 'course-schedule' },
  { num: 125, title: 'Kahn\'s Algorithm', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 10, pattern: 'Topological Sort', description: 'BFS-based topological sorting maintaining in-degree counts array.', linkedProblemId: null },
  { num: 126, title: 'Union Find (DSU)', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 10, pattern: 'Union Find', description: 'Disjoint set data structure supporting find and union in nearly O(1) amortized time.', linkedProblemId: null },
  { num: 127, title: 'Kruskal\'s MST', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 16, pattern: 'Union Find', description: 'Greedy Minimum Spanning Tree algorithm sorting edges by weight and unioning components via DSU.', linkedProblemId: null },
  { num: 128, title: 'Prim\'s MST', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 16, pattern: 'Priority Queue', description: 'Greedy MST algorithm expanding minimum edge connected to current tree via Priority Queue.', linkedProblemId: null },
  { num: 129, title: 'Dijkstra', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 10, pattern: 'Dijkstra', description: 'Single-source shortest path algorithm for non-negative weighted graphs using Min Heap.', linkedProblemId: 'dijkstra-shortest-path' },
  { num: 130, title: 'Bellman-Ford', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 16, pattern: 'Relaxation', description: 'Shortest path algorithm handling negative edge weights and detecting negative weight cycles in O(V*E).', linkedProblemId: null },
  { num: 131, title: 'Floyd-Warshall', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 16, pattern: '2D DP', description: 'All-pairs shortest path dynamic programming algorithm running in O(V^3) time.', linkedProblemId: null },
  { num: 132, title: 'Shortest Path in DAG', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 10, pattern: 'Topological Sort', description: 'O(V + E) linear time shortest path in Directed Acyclic Graphs via topological order relaxation.', linkedProblemId: null },
  { num: 133, title: 'Bridges (Tarjan)', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 16, pattern: 'DFS Discovery Time', description: 'Finding critical edges whose removal increases graph connected components using DFS low-link values.', linkedProblemId: null },
  { num: 134, title: 'Articulation Points', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 16, pattern: 'DFS Discovery Time', description: 'Finding critical vertices whose removal disconnects graph using Tarjan\'s discovery & low time.', linkedProblemId: null },
  { num: 135, title: 'Strongly Connected Components', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 16, pattern: 'DFS', description: 'Subgraphs where every vertex is reachable from any other vertex in directed graph.', linkedProblemId: null },
  { num: 136, title: 'Kosaraju', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 16, pattern: '2-Pass DFS', description: 'Finding SCCs in directed graphs using two DFS passes on original and transposed graphs.', linkedProblemId: null },
  { num: 137, title: 'Tarjan SCC', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 16, pattern: 'DFS Stack', description: 'Single-pass DFS algorithm for strongly connected components using low-link values and stack.', linkedProblemId: null },
  { num: 138, title: 'Bipartite Graph', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 10, pattern: 'BFS/DFS 2-Coloring', description: 'Graph coloring test checking if vertices can be divided into 2 disjoint sets with no internal edges.', linkedProblemId: null },
  { num: 139, title: 'Graph Coloring', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 16, pattern: 'Backtracking', description: 'Assigning colors to vertices such that no adjacent vertices share same color.', linkedProblemId: null },
  { num: 140, title: 'Multi-source BFS', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 10, pattern: 'BFS', description: 'Simultaneous BFS propagation from multiple starting source nodes initialized into queue.', linkedProblemId: null },
  { num: 141, title: '0-1 BFS', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 16, pattern: 'Deque BFS', description: 'O(V + E) shortest path algorithm for graphs with edge weights 0 or 1 using Deque push_front / push_back.', linkedProblemId: null },
  { num: 142, title: 'A* Search (Basics)', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 16, pattern: 'Heuristic Search', description: 'Informed path search algorithm guiding Dijkstra using heuristic distance estimates f(n) = g(n) + h(n).', linkedProblemId: null },
  { num: 143, title: 'Eulerian Path/Circuit', categoryId: 'graphs', categoryName: 'Graphs', priorityTier: 16, pattern: 'Hierholzer\'s Algorithm', description: 'Trail visiting every edge in graph exactly once (Eulerian Circuit returns to start node).', linkedProblemId: null },

  // 13. Dynamic Programming (144..163)
  { num: 144, title: 'Fibonacci DP', categoryId: 'dp', categoryName: 'Dynamic Programming', priorityTier: 12, pattern: '1D DP', description: 'Introductory DP solving f(n) = f(n-1) + f(n-2) using memoization or bottom-up tabulation.', linkedProblemId: 'climbing-stairs' },
  { num: 145, title: 'Memoization', categoryId: 'dp', categoryName: 'Dynamic Programming', priorityTier: 12, pattern: 'Top-Down DP', description: 'Top-down DP storing recursive function return values in memo cache table.', linkedProblemId: null },
  { num: 146, title: 'Tabulation', categoryId: 'dp', categoryName: 'Dynamic Programming', priorityTier: 12, pattern: 'Bottom-Up DP', description: 'Bottom-up DP iteratively filling state transition table from base cases up.', linkedProblemId: null },
  { num: 147, title: 'Space Optimization', categoryId: 'dp', categoryName: 'Dynamic Programming', priorityTier: 12, pattern: 'State Reduction', description: 'Reducing DP table dimension from O(N) to O(1) or O(N^2) to O(N) by keeping active state variables.', linkedProblemId: null },
  { num: 148, title: '0/1 Knapsack', categoryId: 'dp', categoryName: 'Dynamic Programming', priorityTier: 12, pattern: 'Subset DP', description: 'Selecting items with weight and value constraints without repeating item usage.', linkedProblemId: 'knapsack-01' },
  { num: 149, title: 'Unbounded Knapsack', categoryId: 'dp', categoryName: 'Dynamic Programming', priorityTier: 12, pattern: 'Subset DP', description: 'Knapsack variation permitting infinite item re-use (e.g. Coin Change).', linkedProblemId: null },
  { num: 150, title: 'Coin Change', categoryId: 'dp', categoryName: 'Dynamic Programming', priorityTier: 12, pattern: 'Unbounded Knapsack', description: 'Finding minimum coins needed to form target sum.', linkedProblemId: 'coin-change' },
  { num: 151, title: 'Subset Sum', categoryId: 'dp', categoryName: 'Dynamic Programming', priorityTier: 12, pattern: 'Subset DP', description: 'Determining if a non-empty subset exists summing to target integer.', linkedProblemId: null },
  { num: 152, title: 'Partition DP', categoryId: 'dp', categoryName: 'Dynamic Programming', priorityTier: 12, pattern: 'Interval DP', description: 'Splitting array into contiguous valid subsegments to optimize partition costs.', linkedProblemId: null },
  { num: 153, title: 'Matrix Chain Multiplication', categoryId: 'dp', categoryName: 'Dynamic Programming', priorityTier: 12, pattern: 'Interval DP', description: 'Finding optimal parenthesization order for multiplying sequence of matrices with minimal operations.', linkedProblemId: null },
  { num: 154, title: 'Longest Increasing Subsequence', categoryId: 'dp', categoryName: 'Dynamic Programming', priorityTier: 12, pattern: '1D DP / Binary Search', description: 'Finding length of longest strictly increasing subsequence in O(N^2) or O(N log N).', linkedProblemId: null },
  { num: 155, title: 'Longest Common Subsequence', categoryId: 'dp', categoryName: 'Dynamic Programming', priorityTier: 12, pattern: '2D Grid DP', description: 'Finding longest subsequence common to two string sequences in O(M*N) time.', linkedProblemId: 'longest-common-subsequence' },
  { num: 156, title: 'Longest Palindromic Subsequence', categoryId: 'dp', categoryName: 'Dynamic Programming', priorityTier: 12, pattern: 'Interval DP', description: 'Finding longest subsequence in string that reads same forwards and backwards.', linkedProblemId: null },
  { num: 157, title: 'Edit Distance', categoryId: 'dp', categoryName: 'Dynamic Programming', priorityTier: 12, pattern: '2D Grid DP', description: 'Minimum insert, delete, or replace operations to transform string s1 into string s2.', linkedProblemId: null },
  { num: 158, title: 'Digit DP', categoryId: 'dp', categoryName: 'Dynamic Programming', priorityTier: 12, pattern: 'Digit State DP', description: 'Counting numbers in range [1, N] satisfying specific digit properties using digit position state.', linkedProblemId: null },
  { num: 159, title: 'Bitmask DP', categoryId: 'dp', categoryName: 'Dynamic Programming', priorityTier: 12, pattern: 'Bitmask DP', description: 'DP over set subsets using integer bitmask states (e.g., Travelling Salesperson Problem).', linkedProblemId: null },
  { num: 160, title: 'Tree DP', categoryId: 'dp', categoryName: 'Dynamic Programming', priorityTier: 12, pattern: 'Tree Post-order DP', description: 'Dynamic programming state propagation over tree nodes during post-order traversal.', linkedProblemId: null },
  { num: 161, title: 'Interval DP', categoryId: 'dp', categoryName: 'Dynamic Programming', priorityTier: 12, pattern: 'Interval Range DP', description: 'DP states defined over range intervals [i, j] expanding window length from 1 to N.', linkedProblemId: null },
  { num: 162, title: 'State Machine DP', categoryId: 'dp', categoryName: 'Dynamic Programming', priorityTier: 12, pattern: 'Finite State DP', description: 'DP tracking state machine transitions (e.g., Stock Buy/Sell with cooldown or transaction fee).', linkedProblemId: null },
  { num: 163, title: 'DP on Grids', categoryId: 'dp', categoryName: 'Dynamic Programming', priorityTier: 12, pattern: '2D Grid DP', description: 'Path counting and minimum path sum traversals over 2D grid matrix.', linkedProblemId: null },

  // 14. Greedy (164..173)
  { num: 164, title: 'Activity Selection', categoryId: 'greedy', categoryName: 'Greedy', priorityTier: 13, pattern: 'Interval Sorting', description: 'Selecting max count of mutually compatible activities sorted by finish time.', linkedProblemId: null },
  { num: 165, title: 'Fractional Knapsack', categoryId: 'greedy', categoryName: 'Greedy', priorityTier: 13, pattern: 'Value-Density Sorting', description: 'Greedily selecting items by value/weight ratio allowing item fractions.', linkedProblemId: null },
  { num: 166, title: 'Huffman Coding', categoryId: 'greedy', categoryName: 'Greedy', priorityTier: 13, pattern: 'Min Heap Tree', description: 'Optimal prefix-free character data compression algorithm built using Min Heap.', linkedProblemId: null },
  { num: 167, title: 'Job Sequencing', categoryId: 'greedy', categoryName: 'Greedy', priorityTier: 13, pattern: 'Greedy Scheduling', description: 'Maximizing profit by scheduling jobs with deadlines on available time slots.', linkedProblemId: null },
  { num: 168, title: 'Gas Station', categoryId: 'greedy', categoryName: 'Greedy', priorityTier: 13, pattern: 'Greedy Prefix Scan', description: 'Finding starting gas station index to complete circular circuit in O(N).', linkedProblemId: null },
  { num: 169, title: 'Candy Distribution', categoryId: 'greedy', categoryName: 'Greedy', priorityTier: 13, pattern: '2-Pass Greedy Scan', description: 'Distributing minimum candies to children satisfying rating constraints via left & right scans.', linkedProblemId: null },
  { num: 170, title: 'Merge Intervals', categoryId: 'greedy', categoryName: 'Greedy', priorityTier: 13, pattern: 'Greedy Overlap Merge', description: 'Sorting intervals by start time and combining overlapping bounds.', linkedProblemId: 'merge-intervals' },
  { num: 171, title: 'Jump Game', categoryId: 'greedy', categoryName: 'Greedy', priorityTier: 13, pattern: 'Greedy Reach Bounds', description: 'Tracking farthest reachable index at each step to check end destination.', linkedProblemId: null },
  { num: 172, title: 'Minimum Platforms', categoryId: 'greedy', categoryName: 'Greedy', priorityTier: 13, pattern: 'Two Pointers Sorting', description: 'Finding max concurrent trains at railway station by sorting arrival and departure times.', linkedProblemId: null },
  { num: 173, title: 'Greedy Proof Techniques', categoryId: 'greedy', categoryName: 'Greedy', priorityTier: 13, pattern: 'Greedy Choice Proof', description: 'Proving greedy correctness via Exchange Arguments and Stays-Ahead structural induction.', linkedProblemId: null },

  // 15. Backtracking (174..181)
  { num: 174, title: 'N Queens', categoryId: 'backtracking', categoryName: 'Backtracking', priorityTier: 11, pattern: 'Backtracking', description: 'Placing N non-attacking chess queens on N x N board using column and diagonal constraint sets.', linkedProblemId: 'n-queens' },
  { num: 175, title: 'Sudoku Solver', categoryId: 'backtracking', categoryName: 'Backtracking', priorityTier: 11, pattern: 'Backtracking', description: 'Solving 9x9 Sudoku grid by placing digits 1-9 and backtracking on invalid constraints.', linkedProblemId: null },
  { num: 176, title: 'Rat in a Maze', categoryId: 'backtracking', categoryName: 'Backtracking', priorityTier: 11, pattern: 'Backtracking', description: 'Finding path from (0,0) to (N-1, N-1) in grid with blocked obstacle cells.', linkedProblemId: null },
  { num: 177, title: 'Permutations', categoryId: 'backtracking', categoryName: 'Backtracking', priorityTier: 11, pattern: 'Backtracking', description: 'Generating all N! distinct orderings of element array using used-flags array.', linkedProblemId: null },
  { num: 178, title: 'Combinations', categoryId: 'backtracking', categoryName: 'Backtracking', priorityTier: 11, pattern: 'Backtracking', description: 'Generating all C(N, K) subsets of size K from numbers 1..N.', linkedProblemId: null },
  { num: 179, title: 'Combination Sum', categoryId: 'backtracking', categoryName: 'Backtracking', priorityTier: 11, pattern: 'Backtracking', description: 'Finding unique combinations of candidates that sum to target value.', linkedProblemId: null },
  { num: 180, title: 'Word Search', categoryId: 'backtracking', categoryName: 'Backtracking', priorityTier: 11, pattern: 'Grid DFS Backtracking', description: 'Finding if target word exists in 2D character grid using DFS in-place backtracking.', linkedProblemId: null },
  { num: 181, title: 'Palindrome Partitioning', categoryId: 'backtracking', categoryName: 'Backtracking', priorityTier: 11, pattern: 'Backtracking', description: 'Partitioning string into all possible subsegments such that every subsegment is a palindrome.', linkedProblemId: null },

  // 16. Bit Manipulation (182..193)
  { num: 182, title: 'XOR Tricks', categoryId: 'bit-manipulation', categoryName: 'Bit Manipulation', priorityTier: 14, pattern: 'Bitwise XOR', description: 'Properties x ^ x = 0 and x ^ 0 = x for swapping and finding non-repeating numbers.', linkedProblemId: 'single-number' },
  { num: 183, title: 'Bitmasking', categoryId: 'bit-manipulation', categoryName: 'Bit Manipulation', priorityTier: 14, pattern: 'Bitmask', description: 'Representing subset presence using bit positions in integer numbers.', linkedProblemId: null },
  { num: 184, title: 'Set/Clear/Toggle Bits', categoryId: 'bit-manipulation', categoryName: 'Bit Manipulation', priorityTier: 14, pattern: 'Bitwise Operators', description: 'Manipulating specific k-th bit using (1 << k) with OR |, AND &, and XOR ^.', linkedProblemId: null },
  { num: 185, title: 'Count Set Bits', categoryId: 'bit-manipulation', categoryName: 'Bit Manipulation', priorityTier: 14, pattern: 'Kernighan\'s Algorithm', description: 'Counting set bits using n & (n - 1) clearing lowest set bit in O(set bits) time.', linkedProblemId: 'counting-bits' },
  { num: 186, title: 'Power of Two', categoryId: 'bit-manipulation', categoryName: 'Bit Manipulation', priorityTier: 14, pattern: 'Bitwise AND', description: 'Checking if n > 0 and (n & (n - 1)) == 0.', linkedProblemId: null },
  { num: 187, title: 'Single Number', categoryId: 'bit-manipulation', categoryName: 'Bit Manipulation', priorityTier: 14, pattern: 'XOR', description: 'Finding element occurring once where all other elements occur twice using XOR accumulation.', linkedProblemId: 'single-number' },
  { num: 188, title: 'Subsets using Bitmask', categoryId: 'bit-manipulation', categoryName: 'Bit Manipulation', priorityTier: 14, pattern: 'Bitmask Subsets', description: 'Generating all 2^N powerset subsets iterating integer counters from 0 to (1<<N)-1.', linkedProblemId: 'subsets-bitmask' },
  { num: 189, title: 'Gray Code', categoryId: 'bit-manipulation', categoryName: 'Bit Manipulation', priorityTier: 14, pattern: 'Bitwise Shift', description: 'Binary numeral system where two successive values differ in only one bit: n ^ (n >> 1).', linkedProblemId: null },
  { num: 190, title: 'Bitwise DP', categoryId: 'bit-manipulation', categoryName: 'Bit Manipulation', priorityTier: 14, pattern: 'Bitmask DP', description: 'DP state transitions over subset masks.', linkedProblemId: null },
  { num: 191, title: 'Fast Exponentiation', categoryId: 'bit-manipulation', categoryName: 'Bit Manipulation', priorityTier: 14, pattern: 'Binary Exponentiation', description: 'Computing x^n in O(log n) time by inspecting binary bits of exponent n.', linkedProblemId: null },
  { num: 192, title: 'Binary Representation', categoryId: 'bit-manipulation', categoryName: 'Bit Manipulation', priorityTier: 14, pattern: 'Bitwise Shift', description: 'Converting numbers between decimal and binary bit representations.', linkedProblemId: null },
  { num: 193, title: 'AND/OR/XOR Properties', categoryId: 'bit-manipulation', categoryName: 'Bit Manipulation', priorityTier: 14, pattern: 'Boolean Bit Math', description: 'Commutative, associative, and distributive algebraic laws of bitwise operations.', linkedProblemId: null },

  // 17. Mathematical Algorithms (194..203)
  { num: 194, title: 'GCD', categoryId: 'math', categoryName: 'Mathematical Algorithms', priorityTier: 1, pattern: 'Euclidean Algorithm', description: 'Greatest Common Divisor of two integers.', linkedProblemId: null },
  { num: 195, title: 'LCM', categoryId: 'math', categoryName: 'Mathematical Algorithms', priorityTier: 1, pattern: 'GCD Math', description: 'Least Common Multiple calculated via (a * b) / GCD(a, b).', linkedProblemId: null },
  { num: 196, title: 'Euclidean Algorithm', categoryId: 'math', categoryName: 'Mathematical Algorithms', priorityTier: 1, pattern: 'Recursion', description: 'O(log(min(a, b))) recursive GCD algorithm via gcd(a, b) = gcd(b, a % b).', linkedProblemId: null },
  { num: 197, title: 'Sieve of Eratosthenes', categoryId: 'math', categoryName: 'Mathematical Algorithms', priorityTier: 1, pattern: 'Prime Sieve', description: 'Generating all prime numbers up to N in O(N log log N) time.', linkedProblemId: 'sieve-of-eratosthenes' },
  { num: 198, title: 'Prime Factorization', categoryId: 'math', categoryName: 'Mathematical Algorithms', priorityTier: 1, pattern: 'Trial Division', description: 'Decomposing number into prime factors up to sqrt(N) bound.', linkedProblemId: null },
  { num: 199, title: 'Modular Arithmetic', categoryId: 'math', categoryName: 'Mathematical Algorithms', priorityTier: 1, pattern: 'Modulo Math', description: 'Addition, subtraction, and multiplication under modulo arithmetic modulo 10^9+7.', linkedProblemId: null },
  { num: 200, title: 'Fast Modular Exponentiation', categoryId: 'math', categoryName: 'Mathematical Algorithms', priorityTier: 1, pattern: 'Binary Exponentiation', description: 'Computing (base^exp) % mod in logarithmic O(log exp) time.', linkedProblemId: null },
  { num: 201, title: 'Extended Euclid', categoryId: 'math', categoryName: 'Mathematical Algorithms', priorityTier: 1, pattern: 'Extended GCD', description: 'Finding integer coefficients x and y such that ax + by = gcd(a, b) and modular inverse.', linkedProblemId: null },
  { num: 202, title: 'Combinatorics', categoryId: 'math', categoryName: 'Mathematical Algorithms', priorityTier: 1, pattern: 'Factorials / Pascal', description: 'Permutations P(n, k) and combinations C(n, k) computed via Pascal\'s triangle or modular inverse.', linkedProblemId: null },
  { num: 203, title: 'Probability Basics', categoryId: 'math', categoryName: 'Mathematical Algorithms', priorityTier: 1, pattern: 'Expected Value', description: 'Sample space, independent events, Bayes\' theorem, and expected value calculations.', linkedProblemId: null },

  // 18. Advanced Techniques (204..221)
  { num: 204, title: 'Divide and Conquer', categoryId: 'advanced', categoryName: 'Advanced Techniques', priorityTier: 18, pattern: 'Divide and Conquer', description: 'Splitting problems into independent subproblems solved recursively.', linkedProblemId: null },
  { num: 205, title: 'Meet in the Middle', categoryId: 'advanced', categoryName: 'Advanced Techniques', priorityTier: 18, pattern: 'Meet in the Middle', description: 'Reducing exponential search search tree from O(2^N) to O(2^(N/2)).', linkedProblemId: null },
  { num: 206, title: 'Sweep Line', categoryId: 'advanced', categoryName: 'Advanced Techniques', priorityTier: 18, pattern: 'Line Sweep', description: 'Conceptual line sweeping across 2D plane processing geometric event points in sorted order.', linkedProblemId: null },
  { num: 207, title: 'Coordinate Compression', categoryId: 'advanced', categoryName: 'Advanced Techniques', priorityTier: 18, pattern: 'Coordinate Compression', description: 'Replacing large numerical coordinates with their relative 0-indexed sorted rank.', linkedProblemId: null },
  { num: 208, title: 'Prefix XOR', categoryId: 'advanced', categoryName: 'Advanced Techniques', priorityTier: 18, pattern: 'Prefix Math', description: 'Cumulative XOR array allowing O(1) subarray XOR queries.', linkedProblemId: null },
  { num: 209, title: 'Difference Array', categoryId: 'advanced', categoryName: 'Advanced Techniques', priorityTier: 18, pattern: 'Difference Array', description: 'Executing fast constant-time range updates over dynamic arrays.', linkedProblemId: null },
  { num: 210, title: 'Mo\'s Algorithm', categoryId: 'advanced', categoryName: 'Advanced Techniques', priorityTier: 18, pattern: 'Sqrt Decomposition Query Sorting', description: 'Offline range query algorithm sorting queries by sqrt-bucket left boundaries in O((N+Q) * sqrt(N)).', linkedProblemId: null },
  { num: 211, title: 'Convex Hull', categoryId: 'advanced', categoryName: 'Advanced Techniques', priorityTier: 18, pattern: 'Graham Scan / Monotone Chain', description: 'Finding smallest convex polygon enclosing 2D point set in O(N log N) using cross products.', linkedProblemId: null },
  { num: 212, title: 'Line Sweep', categoryId: 'advanced', categoryName: 'Advanced Techniques', priorityTier: 18, pattern: 'Sweep Line', description: 'Solving interval overlap and rectangle area union problems via event-driven sweep line.', linkedProblemId: null },
  { num: 213, title: 'Binary Indexed Tree', categoryId: 'advanced', categoryName: 'Advanced Techniques', priorityTier: 18, pattern: 'Fenwick Tree', description: 'Bit-indexed tree array for logarithmic prefix queries and point updates.', linkedProblemId: null },
  { num: 214, title: 'Segment Tree with Lazy Propagation', categoryId: 'advanced', categoryName: 'Advanced Techniques', priorityTier: 18, pattern: 'Segment Tree', description: 'Range update and range query segment tree using lazy propagation node tags in O(log N).', linkedProblemId: 'segment-tree-rmq' },
  { num: 215, title: 'Persistent Segment Tree', categoryId: 'advanced', categoryName: 'Advanced Techniques', priorityTier: 18, pattern: 'Persistent Tree', description: 'Segment tree creating new path nodes on updates to preserve historical version states.', linkedProblemId: null },
  { num: 216, title: 'Sqrt Decomposition', categoryId: 'advanced', categoryName: 'Advanced Techniques', priorityTier: 18, pattern: 'Sqrt Blocks', description: 'Partitioning array into sqrt(N) blocks to process range updates and queries in O(sqrt(N)).', linkedProblemId: null },
  { num: 217, title: 'Randomized Algorithms', categoryId: 'advanced', categoryName: 'Advanced Techniques', priorityTier: 18, pattern: 'Randomized Pivot/Sampling', description: 'Algorithms using random choices to guarantee fast average-case execution (e.g. Randomized QuickSort).', linkedProblemId: null },
  { num: 218, title: 'Reservoir Sampling', categoryId: 'advanced', categoryName: 'Advanced Techniques', priorityTier: 18, pattern: 'Streaming Sampling', description: 'Randomly selecting K items from an uncounted data stream with uniform 1/N probability.', linkedProblemId: null },
  { num: 219, title: 'String Hashing', categoryId: 'advanced', categoryName: 'Advanced Techniques', priorityTier: 18, pattern: 'Rolling Hash', description: 'Polynomial rolling hash over string prefixes for O(1) dynamic substring equality comparisons.', linkedProblemId: null },
  { num: 220, title: 'Offline Queries', categoryId: 'advanced', categoryName: 'Advanced Techniques', priorityTier: 18, pattern: 'Query Reordering', description: 'Reordering query operations prior to execution to optimize total amortized data structure time.', linkedProblemId: null },
  { num: 221, title: 'Heavy-Light Decomposition', categoryId: 'advanced', categoryName: 'Advanced Techniques', priorityTier: 18, pattern: 'HLD', description: 'Decomposing generic trees into logarithmic heavy paths for Segment Tree range updates.', linkedProblemId: null },
]

export const getTopicsByCategory = (categoryId) => {
  return dsaTopics.filter((t) => t.categoryId === categoryId)
}

export const getTopicsByPriority = (priorityTier) => {
  return dsaTopics.filter((t) => t.priorityTier === priorityTier)
}
